server:
    port: 8080
    servlet:
        context-path: /jodconverter
        encoding:
            charset: utf-8
    compression:
        #启用GZIP压缩功能
        enabled: true
        # 允许压缩的响应缓冲区最小字节数，默认2048
        min-response-size: 2048
        # 压缩格式
        mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain,font/woff,application/font-woff,font/eot,image/svg+xml,image/x-icon
spring:
    servlet:
        multipart:
            # 文件上传限制前端
            max-file-size: 500MB
            #文件上传限制
            max-request-size: 500MB
    freemarker:
        template-loader-path: classpath:/templates/
        cache: false
        charset: UTF-8
        check-template-location: true
        content-type: text/html
        expose-request-attributes: true
        expose-session-attributes: true
        request-context-attribute: request
        suffix: .ftl
    #redis连接，只有当cache.type = redis时才有用
    redisson:
        address: 127.0.0.1:6379
        password:
#提供预览服务的地址，默认从请求url读，如果使用nginx等反向代理，需要手动设置。若为https协议需修改为全路径(例如：https://dev.youshengyun.com/jodconverter)
base:
    url: https://demo-api.youshengyun.com/jodconverter
# 备案信息，默认为空
beian: default
cache:
    #是否启用缓存
    enabled: true
    #缓存实现类型，不配默认为内嵌RocksDB(type = default)实现，可配置为redis(type = redis)实现（需要配置spring.redisson.address等参数）和 JDK 内置对象实现（type = jdk）,
    type: jdk
    clean:
        #缓存是否自动清理 true 为开启，注释掉或其他值都为关闭
        enabled: true
        cron: 0 0 3 * * ?
cad:
    preview:
        #Cad类型图片浏览模式：tif（利用前端js插件浏览）；svg（转换为svg显示）；pdf（转换为pdf后显示，便于打印）
        type: svg
    timeout: 90
    thread: 5
media: mp3,wav,mp4,flv,mpd,m3u8,ts,mpeg,m4a
#是否开启多媒体类型转视频格式转换
media.convert.disable: false
#支持转换的视频类型
convertMedias: avi,mov,wmv,3gp,rm
delete:
    #启用验证码删除文件 默认关闭
    captcha: false
    password: ${JODCONVERTER_DELETE_PASSWORD:123456}
    source:
        #删除 转换后OFFICE、CAD、TIFF、压缩包源文件 默认开启 节约磁盘空间
        file: true
file:
    #预览生成资源路径（默认为打包根路径下的file目录下）
    #WINDOWS参考 D:\\Fileview\\
    dir: /jodconverter/file
    upload:
        #是否禁用首页文件上传
        disable: false
#预览源为FTP时 FTP用户名，可在ftp url后面加参数ftp.username=ftpuser指定，不指定默认用配置的
ftp:
    control:
        encoding: UTF-8
    username: y9admin
    password: 111111
#首页初始化
home:
    pagenumber: 1
    pagination: true
    pagesize: 15
    search: true
local:
    preview:
        #允许预览的本地文件夹 默认不允许任何本地文件被预览
        #WINDOWS参考 D:\\Fileview\\
        dir: default
office:
    # /Libreoffice/Openoffice  驱动的绝对路径
    # home: C:\\Program Files\\LibreOffice
    home: /opt/libreoffice7
    plugin:
        server:
            ## office转换服务的端口，默认开启两个进程
            ports: 2001,2002
        task:
            ## office 转换服务 task 超时时间，默认五分钟
            timeout: 5m
            #此属性设置office进程在重新启动之前可以执行的最大任务数。0表示无限数量的任务（永远不会重新启动）
            maxtasksperprocess: 200
            #此属性设置处理任务所允许的最长时间。如果任务的处理时间长于此超时，则此任务将中止，并处理下一个任务。
            taskexecutiontimeout: 5m
    #生成限制 默认不限制 使用方法 (1-5)
    pagerange: false
    #生成水印 默认不启用 使用方法 (kkFileView)
    watermark: false
    #OFFICE JPEG图片压缩
    quality: 80
    #图像分辨率限制
    maximageresolution: 150
    #导出书签
    exportbookmarks: true
    #批注作为PDF的注释
    exportnotes: true
    #加密文档 生成的PDF文档 添加密码(密码为加密文档的密码)
    documentopenpasswords: true
    type:
        #xlsx格式前端解析
        web: web
    preview:
        #office类型文档(word ppt)样式，默认为图片(image)，可配置为pdf（预览时也有按钮切换）
        type: pdf
        switch:
            #是否关闭office预览切换开关，默认为false，可配置为true关闭
            disabled: false
simText: txt,html,htm,asp,jsp,xml,json,properties,md,gitignore,log,java,py,c,cpp,sql,sh,bat,m,bas,prg,cmd
pdf:
    #PDF转换超时设置 (低于50页)  温馨提示这里数字仅供参考
    timeout: 90
    #PDF转换超时设置 (高于50小于200页)
    timeout80: 180
    #PDF转换超时设置 (大于200页)
    timeout200: 300
    #PDF转换线程设置
    thread: 5
    bookmark:
        #是否禁止bookmark
        disable: false
    download:
        #是否禁止下载转换生成的pdf文件
        disable: false
    disable:
        #是否禁止签名
        editing: false
    presentationMode:
        #是否禁止演示模式
        disable: false
    openFile:
        #是否禁止打开文件
        disable: false
    print:
        #是否禁止打印转换生成的pdf文件
        disable: false
pdf2jpg:
    #配置PDF文件生成图片的像素大小，dpi 越高，图片质量越清晰
    dpi: 144
#禁止上传类型
prohibit: exe,dll,dat
tif:
    preview:
        #Tif类型图片浏览模式：tif（利用前端js插件浏览）；jpg（转换为jpg后前端显示）；pdf（转换为pdf后显示，便于打印）
        type: tif
trust:
    #信任站点，多个用','隔开，设置了之后，会限制只能预览来自信任站点列表的文件，默认不限制
    host: default
not:
    trust:
        #不信任站点，多个用','隔开，设置了之后，会限制来自不信任站点列表的文件，默认不限制
        host: default
watermark:
    alpha: 0.2
    angle: 10
    color: black
    font: 微软雅黑
    fontsize: 18px
    height: 80
    width: 180
    #如需取消水印，内容设置为空即可，例：watermark.txt = ${WATERMARK_TXT:}
    txt:
    x:
        space: 10
    y:
        space: 10