management:
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: 8080
    servlet:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
        session:
            tracking-modes: COOKIE
        context-path: /server-itemddmin
        register-default-servlet: true
    tomcat:
        uri-encoding: UTF-8
spring:
    application:
        name: itemAdmin
    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
            - org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration
            - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
            - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
            - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
    cloud:
        nacos:
            server-addr: https://test.youshengyun.com:443
            username: nacos
            password: ${NACOS_PASSWORD:111111}
            config:
                enabled: false
                group: DEFAULT_GROUP
                namespace: test
            discovery:
                enabled: false
                group: DEFAULT_GROUP
                namespace: test
    config:
        import:
            - optional:nacos:itemAdmin.yml
            #- optional:nacos:test01.yml?group=group_02
            #- optional:nacos:test02.yml?group=group_03&refreshEnabled=false
    data:
        jpa:
            repositories:
                bootstrap-mode: default
                enabled: false
        elasticsearch:
            repositories:
                enabled: true
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            #driver-class-name: com.kingbase8.Driver
            filter:
                stat:
                    log-slow-sql: true
                    mergeSql: true
                    slow-sql-millis: 3000
                wall:
                    config:
                        drop-table-allow: false
                    enabled: true #使用人大金仓数据库要设为false
            stat-view-servlet:
                enabled: false
                url-pattern: /druid/*
                login-username: admin
                login-password: admin
                reset-enable: false
                allow: 127.0.0.1
            web-stat-filter:
                enabled: false
                url-pattern: /*
                exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*,/static/*'
            tenantDefault: spring.datasource.druid.flowable
            y9-public:
                #driver-class-name: oracle.jdbc.OracleDriver
                #url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
                #username: Y9_PUBLIC
                #password: '111111'
                
                #driverClassName: com.kingbase8.Driver
                #url: jdbc:kingbase8://127.0.0.1:54321/risesoft?currentSchema=y9_public
                #username: y9_public
                #password: 111111
                
                driver-class-name: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://localhost:3306/y9_public?serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&useCompression=true&useSSL=false&allowPublicKeyRetrieval=true
                username: root
                password: 111111
                initialSize: 1
                maxActive: 20
                maxPoolPreparedStatementPerConnectionSize: 100
                maxWait: 60000
                minEvictableIdleTimeMillis: 300000
                minIdle: 1
                poolPreparedStatements: true
                testOnBorrow: false
                testOnReturn: false
                testWhileIdle: true
                timeBetweenEvictionRunsMillis: 60000
                useGlobalDataSourceStat: true
                validationQuery: SELECT 1 FROM DUAL
            flowable:
                #driverClassName: com.kingbase8.Driver
                #url: jdbc:kingbase8://127.0.0.1:54321/risesoft?currentSchema=y9_flowable
                #username: y9_flowable
                #password: 111111
                driver-class-name: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://localhost:3306/y9_flowable?serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&useCompression=true&useSSL=false&allowPublicKeyRetrieval=true
                username: root
                password: 111111
                initialSize: 1
                maxActive: 20
                maxPoolPreparedStatementPerConnectionSize: 100
                maxWait: 60000
                minEvictableIdleTimeMillis: 300000
                minIdle: 1
                poolPreparedStatements: true
                testOnBorrow: false
                testOnReturn: false
                testWhileIdle: true
                timeBetweenEvictionRunsMillis: 60000
                useGlobalDataSourceStat: true
                validationQuery: SELECT 1 FROM DUAL
    elasticsearch:
        uris: localhost:9200
        username: elastic
        password: 'risesoft'
    jmx:
        default-domain: itemAdmin
    jpa:
        generate-ddl: true
        hibernate:
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        open-in-view: false
        properties:
            hibernate:
                cache:
                    use_query_cache: false
                    use_second_level_cache: false
                dialect: org.hibernate.dialect.MySQL8Dialect
                hbm2ddl:
                    # 正式环境务必设置为none
                    auto: none
                jdbc:
                    batch_size: 100
                show_sql: false
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            auto-commit-interval: 1000
            enable-auto-commit: true
            group-id: y9itemAdmin-server
    main:
        allow-bean-definition-overriding: true
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    redis:
        database: 8
        host: localhost
        password: 111111
        port: 6379
        lettuce:
            pool:
                max-active: 8
                max-idle: 8
                max-wait: -1
                min-idle: 0
            shutdown-timeout: 100ms
        ssl: false
        timeout: 10000
    servlet:
        multipart:
            max-file-size: 200MB
            max-request-size: 1000MB
y9:
    systemName: itemAdmin
    internalIp: 192.168.x.x,10.x.x.x,172.20.x.x
    app:
        itemAdmin:
            comment: 知悉。,同意。,已阅。,已核。,如拟。,呈XX同志阅示。,呈XX同志审签。,请XX研究办理。,请XX传阅。,请抓紧办理。,请速办。,不同意。,供参考。
            freeFlowKey: ziyouliucheng
            systemCnName: 事项管理
            systemName: itemAdmin
            smsSwitch: false
            weiXinSwitch: true
            weiXinUrl: https://www.youshengyun.com/Youshengyun/Api/pushTempMessage
    service:
        processAdmin:
            directUrl: http://localhost:7056
        msgRemind:
            directUrl: https://dev.youshengyun.com
        datacenter:
            directUrl: https://dev.youshengyun.com
        sms:
            directUrl: http://localhost:7056
        todo:
            directUrl: https://dev.youshengyun.com
        org:
            directUrl: http://localhost:7055
    common:
        cacheEnabled: true
        kafkaEnabled: true
        orgBaseUrl: http://localhost:7055/server-platform
        processAdminBaseUrl: http://localhost:7056/server-processadmin
        itemAdminBaseUrl: http://localhost:7056/server-itemddmin
        datacenterBaseUrl: https://dev.youshengyun.com/server-datacenter
        msgRemindBaseUrl: https://dev.youshengyun.com/server-msgremind
        smsBaseUrl: http://localhost:7056/sms
        todoBaseUrl: https://dev.youshengyun.com/server-todo
        flowableBaseUrl: https://dev.youshengyun.com/flowableUI/index
        logBaseUrl: http://localhost:7056/server-log
        userOnlineBaseUrl: http://localhost:7056/server-useronline
        todo3rdUrl: http://localhost:7057/server-itemadmin
    feature:
        file:
            base64FileName: false
            encryptionFileContent: false
            #privateKey:
            #publicKey:
            rest:
                fileManagerUrl: http://localhost:8080/filemanager
            ftp:
                host: nexus-internal.youshengyun.com
                port: 21
                username: y9admin
                password: '83204585'
                blockWhenExhausted: true
                bufferSize: 10240
                connectTimeOut: 50000
                controlEncoding: UTF-8
                dataTimeout: 1200000
                fileType: 2
                maxIdle: 10
                maxTotal: 50
                minIdle: 2
                maxWaitMillis: 5400000
                testOnBorrow: true
                testOnCreate: true
                testOnReturn: true
                testWhileIdle: true
                useEPSVwithIPv4: false
                passiveMode: true
        elasticsearch:
            packagesToScanEntityPublic: net.risesoft.nosql.elastic.entity
            packagesToScanRepositoryPublic: net.risesoft.nosql.elastic.repository
        jpa:
            packagesToScanEntityPublic: net.risesoft.y9public.entity
            packagesToScanEntityTenant: net.risesoft.entity
            packagesToScanRepositoryPublic: net.risesoft.y9public.repository
            packagesToScanRepositoryTenant: net.risesoft.repository
        listener:
            kafka:
                enabled: false
        liquibase:
            tenant-enabled: true
        multi-tenant:
            # kafka, db
            event-source: kafka
        log:
            enabled: true
            # kafka, api
            reportMethod: kafka
        session:
            redis:
                enabled: true
                maxInactiveIntervalInSeconds: 3600
        security:
            enabled: true
            csrf:
                accepted-referer:
                    - youshengyun.com
                    - localhost
                    - 127.0.0.1
                    - 192.168.3.120
            cors:
                allowCredentials: true
                allowed-headers: '*'
                allowedOriginPatterns:
                    - https://*.youshengyun.com
                    - http://*.youshengyun.com
                    - http://localhost:7055
                    - http://localhost:7056
                    - http://localhost:8080
                    - http://localhost:8081
                    - http://127.0.0.1:7055
                    - http://127.0.0.1:7056
                    - http://localhost:17056
                    - http://127.0.0.1:17056
                    - http://192.168.3.120:8081
            xss:
                ignoreParam:
                    - itemJson
                    - jsonData
                    - formJson
                    - formJsonData
                    - fieldJson
                    - tables
                    - fields
                    - formJsonData
                    - searchMapStr
                    - title
                    - documentTitle
                    - fileName
                    - code
        oauth2:
            resource:
                enabled: true
                allowBasicAuthentication: true
                allowFormEncodedBodyParameter: true
                allowUriQueryParameter: true
                protectedUrlPatterns: /vue/*
                opaque:
                    client-id: clientid_oidc
                    client-secret: secret_oidc
                    introspection-uri: http://localhost:7055/sso/oidc/introspect
                    profile-uri: http://localhost:7055/sso/oidc/profile
