CREATE TABLE "ACT_HI_ACTINST_Year4Table"
(
    "ID_" NVARCHAR2(64) NOT NULL,
    "REV_" INTEGER DEFAULT 1,
    "PROC_DEF_ID_" NVARCHAR2(64) NOT NULL,
    "PROC_INST_ID_" NVARCHAR2(64) NOT NULL,
    "EXECUTION_ID_" NVARCHAR2(64) NOT NULL,
    "ACT_ID_" NVARCHAR2(255) NOT NULL,
    "TASK_ID_" NVARCHAR2(64),
    "CALL_PROC_INST_ID_" NVARCHAR2(64),
    "ACT_NAME_" NVARCHAR2(255),
    "ACT_TYPE_" NVARCHAR2(255) NOT NULL,
    "ASSIGNEE_" NVARCHAR2(255),
    "START_TIME_" TIMESTAMP(6) NOT NULL,
    "END_TIME_" TIMESTAMP(6),
    "TRANSACTION_ORDER_" INTEGER,
    "DURATION_" NUMBER(19,0),
    "DELETE_REASON_" NVARCHAR2(2000),
    "TENANT_ID_" NVARCHAR2(255) DEFAULT '',
    NOT CLUSTER PRIMARY KEY("ID_")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE OR REPLACE  INDEX "ACT_IDX_HI_ACT_INST_START_Year4Table" ON "ACT_HI_ACTINST_Year4Table"("START_TIME_" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE  INDEX "ACT_IDX_HI_ACT_INST_END_Year4Table" ON "ACT_HI_ACTINST_Year4Table"("END_TIME_" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE  INDEX "ACT_IDX_HI_ACT_INST_PROCINST_Year4Table" ON "ACT_HI_ACTINST_Year4Table"("PROC_INST_ID_" ASC,"ACT_ID_" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE  INDEX "ACT_IDX_HI_ACT_INST_EXEC_Year4Table" ON "ACT_HI_ACTINST_Year4Table"("EXECUTION_ID_" ASC,"ACT_ID_" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "ACT_HI_IDENTITYLINK_Year4Table"
(
    "ID_" NVARCHAR2(64) NOT NULL,
    "GROUP_ID_" NVARCHAR2(255),
    "TYPE_" NVARCHAR2(255),
    "USER_ID_" NVARCHAR2(255),
    "TASK_ID_" NVARCHAR2(64),
    "CREATE_TIME_" TIMESTAMP(6),
    "PROC_INST_ID_" NVARCHAR2(64),
    "SCOPE_ID_" NVARCHAR2(255),
    "SUB_SCOPE_ID_" NVARCHAR2(255),
    "SCOPE_TYPE_" NVARCHAR2(255),
    "SCOPE_DEFINITION_ID_" NVARCHAR2(255),
    NOT CLUSTER PRIMARY KEY("ID_")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE OR REPLACE  INDEX "ACT_IDX_HI_IDENT_LNK_USER_Year4Table" ON "ACT_HI_IDENTITYLINK_Year4Table"("USER_ID_" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE  INDEX "ACT_IDX_HI_IDENT_LNK_SCOPE_Year4Table" ON "ACT_HI_IDENTITYLINK_Year4Table"("SCOPE_ID_" ASC,"SCOPE_TYPE_" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE  INDEX "ACT_IDX_HI_IDENT_LNK_SUB_SCOPE_Year4Table" ON "ACT_HI_IDENTITYLINK_Year4Table"("SUB_SCOPE_ID_" ASC,"SCOPE_TYPE_" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE  INDEX "ACT_IDX_HI_IDENT_LNK_SCOPE_DEF_Year4Table" ON "ACT_HI_IDENTITYLINK_Year4Table"("SCOPE_DEFINITION_ID_" ASC,"SCOPE_TYPE_" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE  INDEX "ACT_IDX_HI_IDENT_LNK_TASK_Year4Table" ON "ACT_HI_IDENTITYLINK_Year4Table"("TASK_ID_" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE  INDEX "ACT_IDX_HI_IDENT_LNK_PROCINST_Year4Table" ON "ACT_HI_IDENTITYLINK_Year4Table"("PROC_INST_ID_" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "ACT_HI_PROCINST_Year4Table"
(
    "ID_" NVARCHAR2(64) NOT NULL,
    "REV_" INTEGER DEFAULT 1,
    "PROC_INST_ID_" NVARCHAR2(64) NOT NULL,
    "BUSINESS_KEY_" NVARCHAR2(255),
    "PROC_DEF_ID_" NVARCHAR2(64) NOT NULL,
    "START_TIME_" TIMESTAMP(6) NOT NULL,
    "END_TIME_" TIMESTAMP(6),
    "DURATION_" NUMBER(19,0),
    "START_USER_ID_" NVARCHAR2(255),
    "START_ACT_ID_" NVARCHAR2(255),
    "END_ACT_ID_" NVARCHAR2(255),
    "SUPER_PROCESS_INSTANCE_ID_" NVARCHAR2(64),
    "DELETE_REASON_" NVARCHAR2(2000),
    "TENANT_ID_" NVARCHAR2(255) DEFAULT '',
    "NAME_" NVARCHAR2(255),
    "CALLBACK_ID_" NVARCHAR2(255),
    "CALLBACK_TYPE_" NVARCHAR2(255),
    "REFERENCE_ID_" NVARCHAR2(255),
    "REFERENCE_TYPE_" NVARCHAR2(255),
    "PROPAGATED_STAGE_INST_ID_" NVARCHAR2(255),
    "BUSINESS_STATUS_" NVARCHAR2(255),
    NOT CLUSTER PRIMARY KEY("ID_"),
    UNIQUE("PROC_INST_ID_")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE OR REPLACE  INDEX "ACT_IDX_HI_PRO_INST_END_Year4Table" ON "ACT_HI_PROCINST_Year4Table"("END_TIME_" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE  INDEX "ACT_IDX_HI_PRO_I_BUSKEY_Year4Table" ON "ACT_HI_PROCINST_Year4Table"("BUSINESS_KEY_" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE  INDEX "ACT_IDX_HI_PRO_SUPER_PROCINST_Year4Table" ON "ACT_HI_PROCINST_Year4Table"("SUPER_PROCESS_INSTANCE_ID_" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "ACT_HI_TASKINST_Year4Table"
(
    "ID_" NVARCHAR2(64) NOT NULL,
    "REV_" INTEGER DEFAULT 1,
    "PROC_DEF_ID_" NVARCHAR2(64),
    "TASK_DEF_ID_" NVARCHAR2(64),
    "TASK_DEF_KEY_" NVARCHAR2(255),
    "PROC_INST_ID_" NVARCHAR2(64),
    "EXECUTION_ID_" NVARCHAR2(64),
    "SCOPE_ID_" NVARCHAR2(255),
    "SUB_SCOPE_ID_" NVARCHAR2(255),
    "SCOPE_TYPE_" NVARCHAR2(255),
    "SCOPE_DEFINITION_ID_" NVARCHAR2(255),
    "PROPAGATED_STAGE_INST_ID_" NVARCHAR2(255),
    "PARENT_TASK_ID_" NVARCHAR2(64),
    "NAME_" NVARCHAR2(255),
    "DESCRIPTION_" NVARCHAR2(2000),
    "OWNER_" NVARCHAR2(255),
    "ASSIGNEE_" NVARCHAR2(255),
    "START_TIME_" TIMESTAMP(6) NOT NULL,
    "CLAIM_TIME_" TIMESTAMP(6),
    "END_TIME_" TIMESTAMP(6),
    "DURATION_" NUMBER(19,0),
    "DELETE_REASON_" NVARCHAR2(2000),
    "PRIORITY_" INTEGER,
    "DUE_DATE_" TIMESTAMP(6),
    "FORM_KEY_" NVARCHAR2(255),
    "CATEGORY_" NVARCHAR2(255),
    "TENANT_ID_" NVARCHAR2(255) DEFAULT '',
    "LAST_UPDATED_TIME_" TIMESTAMP(6),
    NOT CLUSTER PRIMARY KEY("ID_")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE OR REPLACE  INDEX "ACT_IDX_HI_TASK_SCOPE_Year4Table" ON "ACT_HI_TASKINST_Year4Table"("SCOPE_ID_" ASC,"SCOPE_TYPE_" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE  INDEX "ACT_IDX_HI_TASK_SUB_SCOPE_Year4Table" ON "ACT_HI_TASKINST_Year4Table"("SUB_SCOPE_ID_" ASC,"SCOPE_TYPE_" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE  INDEX "ACT_IDX_HI_TASK_SCOPE_DEF_Year4Table" ON "ACT_HI_TASKINST_Year4Table"("SCOPE_DEFINITION_ID_" ASC,"SCOPE_TYPE_" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE  INDEX "ACT_IDX_HI_TASK_INST_PROCINST_Year4Table" ON "ACT_HI_TASKINST_Year4Table"("PROC_INST_ID_" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "ACT_HI_VARINST_Year4Table"
(
    "ID_" NVARCHAR2(64) NOT NULL,
    "REV_" INTEGER DEFAULT 1,
    "PROC_INST_ID_" NVARCHAR2(64),
    "EXECUTION_ID_" NVARCHAR2(64),
    "TASK_ID_" NVARCHAR2(64),
    "NAME_" NVARCHAR2(255) NOT NULL,
    "VAR_TYPE_" NVARCHAR2(100),
    "SCOPE_ID_" NVARCHAR2(255),
    "SUB_SCOPE_ID_" NVARCHAR2(255),
    "SCOPE_TYPE_" NVARCHAR2(255),
    "BYTEARRAY_ID_" NVARCHAR2(64),
    "DOUBLE_" NUMBER(38,10),
    "LONG_" NUMBER(19,0),
    "TEXT_" NVARCHAR2(2000),
    "TEXT2_" NVARCHAR2(2000),
    "CREATE_TIME_" TIMESTAMP(6),
    "LAST_UPDATED_TIME_" TIMESTAMP(6),
    NOT CLUSTER PRIMARY KEY("ID_")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE OR REPLACE  INDEX "ACT_IDX_HI_PROCVAR_NAME_TYPE_Year4Table" ON "ACT_HI_VARINST_Year4Table"("NAME_" ASC,"VAR_TYPE_" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE  INDEX "ACT_IDX_HI_VAR_SCOPE_ID_TYPE_Year4Table" ON "ACT_HI_VARINST_Year4Table"("SCOPE_ID_" ASC,"SCOPE_TYPE_" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE  INDEX "ACT_IDX_HI_VAR_SUB_ID_TYPE_Year4Table" ON "ACT_HI_VARINST_Year4Table"("SUB_SCOPE_ID_" ASC,"SCOPE_TYPE_" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE  INDEX "ACT_IDX_HI_PROCVAR_PROC_INST_Year4Table" ON "ACT_HI_VARINST_Year4Table"("PROC_INST_ID_" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE  INDEX "ACT_IDX_HI_PROCVAR_TASK_ID_Year4Table" ON "ACT_HI_VARINST_Year4Table"("TASK_ID_" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE OR REPLACE  INDEX "ACT_IDX_HI_PROCVAR_EXE_Year4Table" ON "ACT_HI_VARINST_Year4Table"("EXECUTION_ID_" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "ACT_GE_BYTEARRAY_Year4Table"
(
    "ID_" NVARCHAR2(64) NOT NULL,
    "REV_" INTEGER,
    "NAME_" NVARCHAR2(255),
    "DEPLOYMENT_ID_" NVARCHAR2(64),
    "BYTES_" BLOB,
    "GENERATED_" NUMBER(1,0),
    NOT CLUSTER PRIMARY KEY("ID_"),
    CONSTRAINT "ACT_FK_BYTEARR_DEPL_Year4Table" FOREIGN KEY("DEPLOYMENT_ID_") REFERENCES "ACT_RE_DEPLOYMENT"("ID_"),
    CHECK(GENERATED_ IN (1, 0))) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE OR REPLACE  INDEX "ACT_IDX_BYTEAR_DEPL_Year4Table" ON "ACT_GE_BYTEARRAY_Year4Table"("DEPLOYMENT_ID_" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;


CREATE TABLE "FF_ACT_RU_EXECUTION_Year4Table"
(
    "ID_" varchar(50) NOT NULL,
    "ACT_ID_" varchar(64),
    "IS_ACTIVE_" integer,
    "BUSINESS_KEY_" varchar(255),
    "CACHED_ENT_STATE_" integer,
    "CALLBACK_ID_" varchar(255),
    "CALLBACK_TYPE_" varchar(255),
    "IS_CONCURRENT_" integer,
    "IS_COUNT_ENABLED_" integer,
    "DEADLETTER_JOB_COUNT_" integer,
    "IS_EVENT_SCOPE_" integer,
    "EVT_SUBSCR_COUNT_" integer,
    "ID_LINK_COUNT_" integer,
    "JOB_COUNT_" integer,
    "LOCK_TIME_" datetime(6),
    "IS_MI_ROOT_" integer,
    "NAME_" varchar(255),
    "PARENT_ID_" varchar(64),
    "PROC_DEF_ID_" varchar(64),
    "PROC_INST_ID_" varchar(50) NOT NULL,
    "REV_" integer,
    "ROOT_PROC_INST_ID_" varchar(64),
    "IS_SCOPE_" integer,
    "START_ACT_ID_" varchar(255),
    "START_TIME_" datetime(6),
    "START_USER_ID_" varchar(255),
    "SUPER_EXEC_" varchar(64),
    "SUSP_JOB_COUNT_" integer,
    "SUSPENSION_STATE_" integer,
    "TASK_COUNT_" integer,
    "TENANT_ID_" varchar(255),
    "TIMER_JOB_COUNT_" integer,
    "VAR_COUNT_" integer,
    NOT CLUSTER PRIMARY KEY("ID_")) STORAGE(ON "MAIN", CLUSTERBTR) ;


