/*
Navicat Oracle Data Transfer
Oracle Client Version : 11.2.0.3.0

Source Server         : 本地-y9_flowable
Source Server Version : 110200
Source Host           : 127.0.0.1:1521
Source Schema         : Y9_FLOWABLE

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2019-05-20 18:11:48
*/


-- ----------------------------
-- Table structure for FF_APPROVEITEM
-- ----------------------------
CREATE TABLE "FF_APPROVEITEM" (
"ID" VARCHAR2(50 CHAR) NOT NULL ,
"ACCOUNTABILITY" VARCHAR2(200 CHAR) NULL ,
"APPURL" VARCHAR2(200 CHAR) NULL ,
"BASICFORMID" VARCHAR2(50 CHAR) NULL ,
"CREATEDATE" TIMESTAMP(6)  NULL ,
"CREATERID" VARCHAR2(255 CHAR) NULL ,
"CREATERNAME" VARCHAR2(255 CHAR) NULL ,
"DEPARTMENTID" VARCHAR2(255 CHAR) NULL ,
"DEPARTMENTNAME" VARCHAR2(255 CHAR) NULL ,
"EXPIRED" NUMBER(10) NULL ,
"HANDELFORMID" VARCHAR2(50 CHAR) NULL ,
"ICONDATA" CLOB NULL ,
"ICONID" VARCHAR2(200 CHAR) NULL ,
"ISDOCKING" VARCHAR2(50 CHAR) NULL ,
"ISONLINE" VARCHAR2(50 CHAR) NULL ,
"LEGALLIMIT" NUMBER(10) NULL ,
"NAME" VARCHAR2(200 CHAR) NOT NULL ,
"NATURE" VARCHAR2(200 CHAR) NULL ,
"REVISEDATE" TIMESTAMP(6)  NULL ,
"REVISERID" VARCHAR2(50 CHAR) NULL ,
"REVISERNAME" VARCHAR2(50 CHAR) NULL ,
"STARTER" VARCHAR2(50 CHAR) NULL ,
"STARTERID" VARCHAR2(50 CHAR) NULL ,
"SYSLEVEL" VARCHAR2(50 CHAR) NULL ,
"SYSTEMNAME" VARCHAR2(50 CHAR) NULL ,
"TYPE" VARCHAR2(50 CHAR) NULL ,
"WORKFLOWGUID" VARCHAR2(100 CHAR) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_ASSOCIATEDFILE
-- ----------------------------
CREATE TABLE "FF_ASSOCIATEDFILE" (
"ID" VARCHAR2(50 CHAR) NOT NULL ,
"ASSOCIATEDID" CLOB NULL ,
"CREATETIME" TIMESTAMP(6)  NULL ,
"PROCESSINSTANCEID" CLOB NULL ,
"PROCESSSERIALNUMBER" CLOB NOT NULL ,
"TENANTID" VARCHAR2(50 CHAR) NOT NULL ,
"USERID" VARCHAR2(50 CHAR) NULL ,
"USERNAME" VARCHAR2(50 CHAR) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_ATTACHMENT
-- ----------------------------
CREATE TABLE "FF_ATTACHMENT" (
"ID" VARCHAR2(38 CHAR) NOT NULL ,
"DELETETIME" VARCHAR2(100 CHAR) NULL ,
"DELETED" NUMBER(10) NULL ,
"DESCRIBES" VARCHAR2(255 CHAR) NULL ,
"DETELEUSERID" VARCHAR2(38 CHAR) NULL ,
"FILESIZE" VARCHAR2(20 CHAR) NULL ,
"FILESOURCE" VARCHAR2(50 CHAR) NULL ,
"FILESTOREID" VARCHAR2(50 CHAR) NULL ,
"FILETYPE" VARCHAR2(20 CHAR) NULL ,
"FILENAME" VARCHAR2(100 CHAR) NULL ,
"PERSONID" VARCHAR2(50 CHAR) NULL ,
"PERSONNAME" VARCHAR2(100 CHAR) NULL ,
"PROCESSINSTANCEID" VARCHAR2(38 CHAR) NULL ,
"PROCESSSERIALNUMBER" VARCHAR2(50 CHAR) NULL ,
"SERIALNUMBER" NUMBER(10) NULL ,
"TABINDEX" NUMBER(10) NULL ,
"TASKID" VARCHAR2(38 CHAR) NULL ,
"UPLOADTIME" VARCHAR2(100 CHAR) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_AUTOFORMSEQUENCE
-- ----------------------------
CREATE TABLE "FF_AUTOFORMSEQUENCE" (
"ID" VARCHAR2(50 CHAR) NOT NULL ,
"CALENDARYEAR" NUMBER(10) NULL ,
"CHARACTERVALUE" VARCHAR2(255 CHAR) NULL ,
"LABELNAME" VARCHAR2(255 CHAR) NULL ,
"SEQUENCEVALUE" NUMBER(10) NULL ,
"TENANTID" VARCHAR2(50 CHAR) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_CHAOSONG
-- ----------------------------
CREATE TABLE "FF_CHAOSONG" (
"ID" VARCHAR2(50 CHAR) NOT NULL ,
"CREATETIME" VARCHAR2(100 CHAR) NULL ,
"ITEMID" VARCHAR2(50 CHAR) NOT NULL ,
"ITEMNAME" VARCHAR2(100 CHAR) NOT NULL ,
"PROCESSINSTANCEID" VARCHAR2(50 CHAR) NOT NULL ,
"PROCESSSERIALNUMBER" VARCHAR2(50 CHAR) NOT NULL ,
"READTIME" VARCHAR2(100 CHAR) NULL ,
"SENDERID" VARCHAR2(100 CHAR) NULL ,
"SENDERNAME" VARCHAR2(50 CHAR) NULL ,
"STATUS" NUMBER(10) NULL ,
"SYSTEMNAME" VARCHAR2(50 CHAR) NOT NULL ,
"TASKID" VARCHAR2(50 CHAR) NOT NULL ,
"TENANTID" VARCHAR2(50 CHAR) NOT NULL ,
"TITLE" CLOB NOT NULL ,
"USERID" VARCHAR2(100 CHAR) NOT NULL ,
"USERNAME" VARCHAR2(50 CHAR) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_COMMONBUTTON
-- ----------------------------
CREATE TABLE "FF_COMMONBUTTON" (
"ID" VARCHAR2(38 CHAR) NOT NULL ,
"CREATETIME" VARCHAR2(255 CHAR) NULL ,
"CUSTOMID" VARCHAR2(50 CHAR) NOT NULL ,
"NAME" VARCHAR2(50 CHAR) NOT NULL ,
"TENANTID" VARCHAR2(50 CHAR) NOT NULL ,
"UPDATETIME" VARCHAR2(255 CHAR) NULL ,
"USERID" VARCHAR2(50 CHAR) NULL ,
"USERNAME" VARCHAR2(50 CHAR) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_COMMONSENTENCES
-- ----------------------------
CREATE TABLE "FF_COMMONSENTENCES" (
"ID" VARCHAR2(38 CHAR) NOT NULL ,
"CONTENT" VARCHAR2(4000 CHAR) NOT NULL ,
"TABINDEX" NUMBER(10) NULL ,
"TENANTID" VARCHAR2(50 CHAR) NOT NULL ,
"USERID" VARCHAR2(38 CHAR) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_COMMONSENTENCESINIT
-- ----------------------------
CREATE TABLE "FF_COMMONSENTENCESINIT" (
"ID" VARCHAR2(38 CHAR) NOT NULL ,
"USERID" VARCHAR2(38 CHAR) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_DOCUMENTNUMBERDETAIL
-- ----------------------------
CREATE TABLE "FF_DOCUMENTNUMBERDETAIL" (
"ID" VARCHAR2(50 CHAR) NOT NULL ,
"CALENDARYEAR" NUMBER(10) NOT NULL ,
"NUMLENGTH" NUMBER(10) NULL ,
"SEQUENCEINITVALUE" NUMBER(10) NULL ,
"TENANTID" VARCHAR2(50 CHAR) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_DOCUMENTWORD
-- ----------------------------
CREATE TABLE "FF_DOCUMENTWORD" (
"ID" VARCHAR2(38 CHAR) NOT NULL ,
"DELETED" VARCHAR2(10 CHAR) NULL ,
"FILENAME" VARCHAR2(1000 CHAR) NULL ,
"FILESIZE" VARCHAR2(10 CHAR) NULL ,
"FILESTOREID" VARCHAR2(50 CHAR) NULL ,
"FILETYPE" VARCHAR2(50 CHAR) NULL ,
"ISTAOHONG" VARCHAR2(10 CHAR) NULL ,
"PROCESSINSTANCEID" VARCHAR2(64 CHAR) NULL ,
"PROCESSSERIALNUMBER" VARCHAR2(38 CHAR) NULL ,
"SAVEDATE" VARCHAR2(100 CHAR) NULL ,
"TENANTID" VARCHAR2(50 CHAR) NOT NULL ,
"TITLE" VARCHAR2(1000 CHAR) NULL ,
"USERID" VARCHAR2(38 CHAR) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_DOCUMENTWORD_HIS
-- ----------------------------
CREATE TABLE "FF_DOCUMENTWORD_HIS" (
"ID" VARCHAR2(38 CHAR) NOT NULL ,
"DELETED" VARCHAR2(10 CHAR) NULL ,
"FILENAME" VARCHAR2(1000 CHAR) NULL ,
"FILESIZE" VARCHAR2(10 CHAR) NULL ,
"FILESTOREID" VARCHAR2(50 CHAR) NULL ,
"FILETYPE" VARCHAR2(50 CHAR) NULL ,
"ISTAOHONG" VARCHAR2(10 CHAR) NULL ,
"PROCESSINSTANCEID" VARCHAR2(64 CHAR) NULL ,
"PROCESSSERIALNUMBER" VARCHAR2(38 CHAR) NULL ,
"SAVEDATE" VARCHAR2(38 CHAR) NULL ,
"TASKID" VARCHAR2(50 CHAR) NULL ,
"TENANTID" VARCHAR2(50 CHAR) NOT NULL ,
"TITLE" VARCHAR2(1000 CHAR) NULL ,
"USERID" VARCHAR2(38 CHAR) NOT NULL ,
"VERSION" NUMBER(10) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_DRAFTENTITY
-- ----------------------------
CREATE TABLE "FF_DRAFTENTITY" (
"ID" VARCHAR2(38 CHAR) NOT NULL ,
"CREATER" VARCHAR2(200 CHAR) NULL ,
"CREATERID" VARCHAR2(50 CHAR) NULL ,
"DELFLAG" NUMBER(1) NULL ,
"DOCNUMBER" VARCHAR2(50 CHAR) NULL ,
"DRAFTTIME" TIMESTAMP(6)  NULL ,
"ITEMID" VARCHAR2(50 CHAR) NULL ,
"PROCESSDEFINITIONKEY" VARCHAR2(100 CHAR) NULL ,
"PROCESSINSTANCEID" VARCHAR2(50 CHAR) NULL ,
"PROCESSSERIALNUMBER" VARCHAR2(50 CHAR) NULL ,
"SERIALNUMBER" NUMBER(10) NULL ,
"SYSTEMNAME" VARCHAR2(50 CHAR) NULL ,
"TITLE" VARCHAR2(1500 CHAR) NULL ,
"TYPE" VARCHAR2(100 CHAR) NULL ,
"URGENCY" VARCHAR2(20 CHAR) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_DYNAMICROLE
-- ----------------------------
CREATE TABLE "FF_DYNAMICROLE" (
"ID" VARCHAR2(255 CHAR) NOT NULL ,
"CLASSPATH" VARCHAR2(500 CHAR) NOT NULL ,
"DESCRIPTION" CLOB NULL ,
"NAME" VARCHAR2(255 CHAR) NULL ,
"TABINDEX" NUMBER(10) NULL ,
"TENANTID" VARCHAR2(50 CHAR) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_ENTRUST
-- ----------------------------
CREATE TABLE "FF_ENTRUST" (
"ID" VARCHAR2(38 CHAR) NOT NULL ,
"ASSIGNEEID" VARCHAR2(100 CHAR) NOT NULL ,
"CREATTIME" VARCHAR2(255 CHAR) NOT NULL ,
"ENDTIME" VARCHAR2(30 CHAR) NOT NULL ,
"ITEMID" VARCHAR2(255 CHAR) NOT NULL ,
"OWNERID" VARCHAR2(100 CHAR) NOT NULL ,
"STARTTIME" VARCHAR2(30 CHAR) NOT NULL ,
"UPDATETIME" VARCHAR2(255 CHAR) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_ENTRUST_HISTORY
-- ----------------------------
CREATE TABLE "FF_ENTRUST_HISTORY" (
"ID" VARCHAR2(38 CHAR) NOT NULL ,
"ASSIGNEEID" VARCHAR2(100 CHAR) NOT NULL ,
"CREATTIME" VARCHAR2(255 CHAR) NOT NULL ,
"ENDTIME" VARCHAR2(30 CHAR) NOT NULL ,
"ITEMID" VARCHAR2(255 CHAR) NOT NULL ,
"OWNERID" VARCHAR2(100 CHAR) NOT NULL ,
"STARTTIME" VARCHAR2(30 CHAR) NOT NULL ,
"UPDATETIME" VARCHAR2(255 CHAR) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_EXTENDED_CONTENT
-- ----------------------------
CREATE TABLE "FF_EXTENDED_CONTENT" (
"ID" VARCHAR2(38 CHAR) NOT NULL ,
"CATEGORY" VARCHAR2(50 CHAR) NOT NULL ,
"CONTENT" VARCHAR2(4000 CHAR) NOT NULL ,
"CREATEDATE" TIMESTAMP(6)  NULL ,
"DEPARTMENTID" VARCHAR2(38 CHAR) NULL ,
"DEPARTMENTNAME" VARCHAR2(50 CHAR) NULL ,
"MODIFYDATE" TIMESTAMP(6)  NULL ,
"PROCESSINSTANCEID" VARCHAR2(64 CHAR) NULL ,
"PROCESSSERIALNUMBER" VARCHAR2(38 CHAR) NOT NULL ,
"TABINDEX" NUMBER(10) NULL ,
"TASKID" VARCHAR2(64 CHAR) NULL ,
"TENANTID" VARCHAR2(50 CHAR) NOT NULL ,
"USERID" VARCHAR2(38 CHAR) NOT NULL ,
"USERNAME" VARCHAR2(50 CHAR) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_EXTRANETEFORMITEMBIND
-- ----------------------------
CREATE TABLE "FF_EXTRANETEFORMITEMBIND" (
"ID" VARCHAR2(38 CHAR) NOT NULL ,
"FORMID" VARCHAR2(38 CHAR) NOT NULL ,
"FORMNAME" VARCHAR2(100 CHAR) NULL ,
"FORMURL" VARCHAR2(100 CHAR) NULL ,
"ITEMID" VARCHAR2(55 CHAR) NOT NULL ,
"ITEMNAME" VARCHAR2(50 CHAR) NULL ,
"TABINDEX" NUMBER(10) NULL ,
"TENANTID" VARCHAR2(50 CHAR) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_ITEM_BUTTON_ROLE
-- ----------------------------
CREATE TABLE "FF_ITEM_BUTTON_ROLE" (
"ID" VARCHAR2(38 CHAR) NOT NULL ,
"ITEMBUTTONID" VARCHAR2(50 CHAR) NOT NULL ,
"ROLEID" VARCHAR2(50 CHAR) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_ITEM_BUTTONBIND
-- ----------------------------
CREATE TABLE "FF_ITEM_BUTTONBIND" (
"ID" VARCHAR2(38 CHAR) NOT NULL ,
"BUTTONID" VARCHAR2(38 CHAR) NOT NULL ,
"BUTTONTYPE" NUMBER(10) NOT NULL ,
"CREATETIME" VARCHAR2(50 CHAR) NULL ,
"ITEMID" VARCHAR2(100 CHAR) NOT NULL ,
"PROCESSDEFINITIONID" VARCHAR2(100 CHAR) NOT NULL ,
"TABINDEX" NUMBER(10) NULL ,
"TASKDEFKEY" VARCHAR2(100 CHAR) NOT NULL ,
"TENANTID" VARCHAR2(50 CHAR) NOT NULL ,
"UPDATETIME" VARCHAR2(50 CHAR) NULL ,
"USERID" VARCHAR2(50 CHAR) NULL ,
"USERNAME" VARCHAR2(50 CHAR) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_ITEM_EFORMBIND
-- ----------------------------
CREATE TABLE "FF_ITEM_EFORMBIND" (
"ID" VARCHAR2(38 CHAR) NOT NULL ,
"ALIAS" VARCHAR2(100 CHAR) NULL ,
"FORMID" VARCHAR2(38 CHAR) NOT NULL ,
"FORMURL" VARCHAR2(100 CHAR) NOT NULL ,
"ITEMID" VARCHAR2(55 CHAR) NOT NULL ,
"PROCESSDEFINITIONID" VARCHAR2(255 CHAR) NOT NULL ,
"SHOWDOCUMENTTAB" NUMBER(1) NULL ,
"SHOWFILETAB" NUMBER(1) NULL ,
"SHOWHISTORYTAB" NUMBER(1) NULL ,
"TABINDEX" NUMBER(10) NULL ,
"TASKDEFKEY" VARCHAR2(255 CHAR) NULL ,
"TENANTID" VARCHAR2(50 CHAR) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_ITEM_OPINIONFRAME
-- ----------------------------
CREATE TABLE "FF_ITEM_OPINIONFRAME" (
"ID" VARCHAR2(38 CHAR) NOT NULL ,
"CREATEDATE" VARCHAR2(255 CHAR) NULL ,
"ITEMID" VARCHAR2(200 CHAR) NOT NULL ,
"MODIFYDATE" VARCHAR2(255 CHAR) NULL ,
"OPINIONFRAMEMARK" VARCHAR2(50 CHAR) NOT NULL ,
"OPINIONFRAMENAME" VARCHAR2(100 CHAR) NOT NULL ,
"PROCESSDEFINITIONID" VARCHAR2(255 CHAR) NOT NULL ,
"TASKDEFKEY" VARCHAR2(100 CHAR) NOT NULL ,
"TENANTID" VARCHAR2(50 CHAR) NOT NULL ,
"USERID" VARCHAR2(50 CHAR) NULL ,
"USERNAME" VARCHAR2(50 CHAR) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_ITEM_OPINIONFRAME_ROLE
-- ----------------------------
CREATE TABLE "FF_ITEM_OPINIONFRAME_ROLE" (
"ID" VARCHAR2(38 CHAR) NOT NULL ,
"ITEMOPINIONFRAMEID" VARCHAR2(50 CHAR) NOT NULL ,
"ROLEID" VARCHAR2(50 CHAR) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_ITEM_ORGANWORD
-- ----------------------------
CREATE TABLE "FF_ITEM_ORGANWORD" (
"ID" VARCHAR2(38 CHAR) NOT NULL ,
"CREATEDATE" VARCHAR2(50 CHAR) NULL ,
"ITEMID" VARCHAR2(50 CHAR) NOT NULL ,
"MODIFYDATE" VARCHAR2(50 CHAR) NULL ,
"ORGANWORDCUSTOM" VARCHAR2(50 CHAR) NOT NULL ,
"PROCESSDEFINITIONID" VARCHAR2(200 CHAR) NOT NULL ,
"TASKDEFKEY" VARCHAR2(100 CHAR) NOT NULL ,
"USERID" VARCHAR2(50 CHAR) NULL ,
"USERNAME" VARCHAR2(50 CHAR) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_ITEM_ORGANWORD_ROLE
-- ----------------------------
CREATE TABLE "FF_ITEM_ORGANWORD_ROLE" (
"ID" VARCHAR2(38 CHAR) NOT NULL ,
"ITEMORGANWORDBINDID" VARCHAR2(50 CHAR) NOT NULL ,
"ROLEID" VARCHAR2(50 CHAR) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_ITEM_PERMISSION
-- ----------------------------
CREATE TABLE "FF_ITEM_PERMISSION" (
"ID" VARCHAR2(255 CHAR) NOT NULL ,
"CREATDATE" VARCHAR2(50 CHAR) NULL ,
"ITEMID" VARCHAR2(55 CHAR) NOT NULL ,
"PROCESSDEFINITIONID" VARCHAR2(255 CHAR) NOT NULL ,
"ROLEID" VARCHAR2(255 CHAR) NULL ,
"ROLETYPE" NUMBER(10) NULL ,
"TABINDEX" NUMBER(10) NULL ,
"TASKDEFKEY" VARCHAR2(255 CHAR) NULL ,
"TENANTID" VARCHAR2(50 CHAR) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_ITEM_PRINTFORM_BIND
-- ----------------------------
CREATE TABLE "FF_ITEM_PRINTFORM_BIND" (
"ID" VARCHAR2(38 CHAR) NOT NULL ,
"CREATETIME" VARCHAR2(50 CHAR) NULL ,
"FORMID" VARCHAR2(38 CHAR) NOT NULL ,
"FORMURL" VARCHAR2(100 CHAR) NOT NULL ,
"ITEMID" VARCHAR2(55 CHAR) NOT NULL ,
"PROCESSDEFINITIONID" VARCHAR2(100 CHAR) NOT NULL ,
"TABINDEX" NUMBER(10) NULL ,
"TENANTID" VARCHAR2(50 CHAR) NOT NULL ,
"UPDATETIME" VARCHAR2(50 CHAR) NULL ,
"USERID" VARCHAR2(50 CHAR) NULL ,
"USERNAME" VARCHAR2(50 CHAR) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_ITEM_TABBIND
-- ----------------------------
CREATE TABLE "FF_ITEM_TABBIND" (
"ID" VARCHAR2(38 CHAR) NOT NULL ,
"CREATETIME" VARCHAR2(50 CHAR) NULL ,
"ITEMID" VARCHAR2(100 CHAR) NOT NULL ,
"PROCESSDEFINITIONID" VARCHAR2(100 CHAR) NOT NULL ,
"TABID" VARCHAR2(38 CHAR) NOT NULL ,
"TABINDEX" NUMBER(10) NULL ,
"TENANTID" VARCHAR2(50 CHAR) NOT NULL ,
"UPDATETIME" VARCHAR2(50 CHAR) NULL ,
"USERID" VARCHAR2(50 CHAR) NULL ,
"USERNAME" VARCHAR2(50 CHAR) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_ITEM_TASKCONF
-- ----------------------------
CREATE TABLE "FF_ITEM_TASKCONF" (
"ID" VARCHAR2(38 CHAR) NOT NULL ,
"ITEMID" VARCHAR2(50 CHAR) NOT NULL ,
"PROCESSDEFINITIONID" VARCHAR2(100 CHAR) NOT NULL ,
"SIGNOPINION" NUMBER(1) DEFAULT 0  NULL ,
"SPONSOR" NUMBER(1) DEFAULT 0  NOT NULL ,
"TASKDEFKEY" VARCHAR2(100 CHAR) NOT NULL ,
"TENANTID" VARCHAR2(50 CHAR) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_ITEM_WORDTEMPLATE_BIND
-- ----------------------------
CREATE TABLE "FF_ITEM_WORDTEMPLATE_BIND" (
"ID" VARCHAR2(255 CHAR) NOT NULL ,
"ITEMID" VARCHAR2(50 CHAR) NULL ,
"PROCESSDEFINITIONID" VARCHAR2(100 CHAR) NOT NULL ,
"TEMPLATEID" VARCHAR2(50 CHAR) NULL ,
"TENANTID" VARCHAR2(50 CHAR) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_NETWORK_WORKORDERINFO
-- ----------------------------
CREATE TABLE "FF_NETWORK_WORKORDERINFO" (
"ID" VARCHAR2(38 CHAR) NOT NULL ,
"ACCEPTANCENOTICE" CLOB NULL ,
"ACCEPTANCETIME" TIMESTAMP(6)  NULL ,
"BUREAUGUID" VARCHAR2(38 CHAR) NULL ,
"BUREAUNAME" VARCHAR2(38 CHAR) NULL ,
"DECLARERGUID" VARCHAR2(50 CHAR) NULL ,
"DECLARERMOBILE" VARCHAR2(50 CHAR) NULL ,
"DECLARERPERSON" VARCHAR2(500 CHAR) NULL ,
"DESCRIPTION" CLOB NULL ,
"EMPLOYEEGUID" VARCHAR2(38 CHAR) NULL ,
"EMPLOYEEMOBILE" VARCHAR2(15 CHAR) NULL ,
"EMPLOYEENAME" VARCHAR2(38 CHAR) NULL ,
"ENDTIME" TIMESTAMP(6)  NULL ,
"FILENAME" VARCHAR2(200 CHAR) NULL ,
"FILEURL" VARCHAR2(500 CHAR) NULL ,
"FINISHNOTICE" CLOB NULL ,
"ISINOROUT" NUMBER(10) NULL ,
"ITEMGUID" VARCHAR2(38 CHAR) NULL ,
"ITEMNAME" VARCHAR2(250 CHAR) NULL ,
"PROCESSDEFINITIONKEY" VARCHAR2(50 CHAR) NULL ,
"PROCESSINSTANCEID" VARCHAR2(50 CHAR) NULL ,
"PROCESSSERIALNUMBER" VARCHAR2(50 CHAR) NULL ,
"PRODUCTMODEL" VARCHAR2(200 CHAR) NULL ,
"STATUS" NUMBER(10) NULL ,
"SUBMITTIME" TIMESTAMP(6)  NULL ,
"TEXT" CLOB NULL ,
"TITLE" VARCHAR2(500 CHAR) NULL ,
"WORKLEVEL" VARCHAR2(50 CHAR) NULL ,
"WORKORDERGRADE" VARCHAR2(200 CHAR) NULL ,
"WORKORDERNO" VARCHAR2(50 CHAR) NULL ,
"WORKORDERTYPE" VARCHAR2(50 CHAR) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_OPINION
-- ----------------------------
CREATE TABLE "FF_OPINION" (
"ID" VARCHAR2(38 CHAR) NOT NULL ,
"CONTENT" CLOB NOT NULL ,
"CREATEDATE" VARCHAR2(50 CHAR) NULL ,
"MODIFYDATE" VARCHAR2(50 CHAR) NULL ,
"OPINIONFRAMEMARK" VARCHAR2(50 CHAR) NOT NULL ,
"PROCESSINSTANCEID" VARCHAR2(64 CHAR) NULL ,
"PROCESSSERIALNUMBER" VARCHAR2(38 CHAR) NOT NULL ,
"TASKID" VARCHAR2(200 CHAR) NULL ,
"TENANTID" VARCHAR2(50 CHAR) NOT NULL ,
"USERID" VARCHAR2(38 CHAR) NOT NULL ,
"USERNAME" VARCHAR2(50 CHAR) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_OPINIONFRAME
-- ----------------------------
CREATE TABLE "FF_OPINIONFRAME" (
"ID" VARCHAR2(38 CHAR) NOT NULL ,
"CREATEDATE" VARCHAR2(255 CHAR) NULL ,
"DELETED" NUMBER(10) NULL ,
"MARK" VARCHAR2(50 CHAR) NOT NULL ,
"MODIFYDATE" VARCHAR2(255 CHAR) NULL ,
"NAME" VARCHAR2(100 CHAR) NOT NULL ,
"TENANTID" VARCHAR2(50 CHAR) NULL ,
"USERID" VARCHAR2(50 CHAR) NOT NULL ,
"USERNAME" VARCHAR2(50 CHAR) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_ORGANWORD
-- ----------------------------
CREATE TABLE "FF_ORGANWORD" (
"ID" VARCHAR2(50 CHAR) NOT NULL ,
"CREATETIME" VARCHAR2(255 CHAR) NULL ,
"CUSTOM" VARCHAR2(50 CHAR) NULL ,
"NAME" VARCHAR2(50 CHAR) NULL ,
"USERNAME" VARCHAR2(50 CHAR) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_ORGANWORD_DETAIL
-- ----------------------------
CREATE TABLE "FF_ORGANWORD_DETAIL" (
"ID" VARCHAR2(50 CHAR) NOT NULL ,
"CHARACTERVALUE" VARCHAR2(50 CHAR) NOT NULL ,
"CREATETIME" VARCHAR2(255 CHAR) NOT NULL ,
"CUSTOM" VARCHAR2(50 CHAR) NOT NULL ,
"ITEMID" VARCHAR2(50 CHAR) NOT NULL ,
"CURRENTNUMBER" NUMBER(10) NOT NULL ,
"TENANTID" VARCHAR2(50 CHAR) NOT NULL ,
"YEARS" NUMBER(10) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_ORGANWORD_PROPTY
-- ----------------------------
CREATE TABLE "FF_ORGANWORD_PROPTY" (
"ID" VARCHAR2(50 CHAR) NOT NULL ,
"INITNUMBER" NUMBER(10) NOT NULL ,
"NAME" VARCHAR2(50 CHAR) NULL ,
"ORGANWORDID" VARCHAR2(50 CHAR) NULL ,
"TABINDEX" NUMBER(10) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_ORGANWORD_USEHISTORY
-- ----------------------------
CREATE TABLE "FF_ORGANWORD_USEHISTORY" (
"ID" VARCHAR2(50 CHAR) NOT NULL ,
"CREATETIME" VARCHAR2(255 CHAR) NOT NULL ,
"CUSTOM" VARCHAR2(50 CHAR) NOT NULL ,
"ITEMID" VARCHAR2(50 CHAR) NOT NULL ,
"NUMBERSTRING" VARCHAR2(50 CHAR) NOT NULL ,
"PROCESSSERIALNUMBER" VARCHAR2(50 CHAR) NOT NULL ,
"TENANTID" VARCHAR2(50 CHAR) NOT NULL ,
"USERID" VARCHAR2(50 CHAR) NOT NULL ,
"USERNAME" VARCHAR2(50 CHAR) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_PROCESSTRACK
-- ----------------------------
CREATE TABLE "FF_PROCESSTRACK" (
"ID" VARCHAR2(50 CHAR) NOT NULL ,
"DESCRIBED" VARCHAR2(500 CHAR) NULL ,
"ENDTIME" VARCHAR2(50 CHAR) NULL ,
"PROCESSINSTANCEID" VARCHAR2(50 CHAR) NOT NULL ,
"RECEIVERNAME" VARCHAR2(50 CHAR) NULL ,
"SENDERNAME" VARCHAR2(255 CHAR) NOT NULL ,
"STARTTIME" VARCHAR2(50 CHAR) NULL ,
"TASKDEFNAME" VARCHAR2(50 CHAR) NULL ,
"TASKID" VARCHAR2(50 CHAR) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_PROCINSTANCERELATIONSHIP
-- ----------------------------
CREATE TABLE "FF_PROCINSTANCERELATIONSHIP" (
"PROCINSTANCEID" VARCHAR2(255 CHAR) NOT NULL ,
"PARENTPROCINSTANCEID" VARCHAR2(255 CHAR) NULL ,
"PROCDEFINITIONKEY" VARCHAR2(255 CHAR) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_REJECTREASON
-- ----------------------------
CREATE TABLE "FF_REJECTREASON" (
"ID" VARCHAR2(50 CHAR) NOT NULL ,
"ACTION" NUMBER(10) NULL ,
"REASON" VARCHAR2(1000 CHAR) NULL ,
"TASKID" VARCHAR2(50 CHAR) NULL ,
"USERID" VARCHAR2(100 CHAR) NULL ,
"USERMOBILE" VARCHAR2(255 CHAR) NULL ,
"USERNAME" VARCHAR2(255 CHAR) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_REMINDER
-- ----------------------------
CREATE TABLE "FF_REMINDER" (
"ID" VARCHAR2(38 CHAR) NOT NULL ,
"CREATETIME" TIMESTAMP(6)  NOT NULL ,
"MODIFYTIME" TIMESTAMP(6)  NOT NULL ,
"MSGCONTENT" VARCHAR2(1000 CHAR) NOT NULL ,
"PROCINSTID" VARCHAR2(64 CHAR) NOT NULL ,
"READTIME" TIMESTAMP(6)  NULL ,
"REMINDER_MAKE_TYPE" NUMBER(10) NOT NULL ,
"REMINDER_SEND_TYPE" VARCHAR2(50 CHAR) NOT NULL ,
"SENDERID" VARCHAR2(38 CHAR) NOT NULL ,
"SENDERNAME" VARCHAR2(10 CHAR) NOT NULL ,
"TASKID" VARCHAR2(64 CHAR) NOT NULL ,
"TENANTID" VARCHAR2(50 CHAR) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_REMINDERDEFINE
-- ----------------------------
CREATE TABLE "FF_REMINDERDEFINE" (
"ID" VARCHAR2(38 CHAR) NOT NULL ,
"CUSTOMID" VARCHAR2(50 CHAR) NULL ,
"DAY_TYPE" NUMBER(10) NOT NULL ,
"MSGTEMPLATE" VARCHAR2(500 CHAR) NOT NULL ,
"PROCESSDEFINITIONID" VARCHAR2(64 CHAR) NOT NULL ,
"REMINDCOUNT" NUMBER(10) NULL ,
"REMINDINTERVAL" NUMBER(10) NULL ,
"REMINDSTART" NUMBER(10) NULL ,
"REMINDERDEFINE_AUTOMATIC" NUMBER(10) NOT NULL ,
"REMINDERDEFINE_TYPE" VARCHAR2(50 CHAR) NOT NULL ,
"TASKDEFKEY" VARCHAR2(255 CHAR) NULL ,
"TASKDURATION" NUMBER(10) NULL ,
"TENANTID" VARCHAR2(50 CHAR) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_SENDBUTTON
-- ----------------------------
CREATE TABLE "FF_SENDBUTTON" (
"ID" VARCHAR2(38 CHAR) NOT NULL ,
"CREATETIME" VARCHAR2(255 CHAR) NULL ,
"CUSTOMID" VARCHAR2(50 CHAR) NOT NULL ,
"NAME" VARCHAR2(50 CHAR) NOT NULL ,
"TENANTID" VARCHAR2(50 CHAR) NOT NULL ,
"UPDATETIME" VARCHAR2(255 CHAR) NULL ,
"USERID" VARCHAR2(50 CHAR) NULL ,
"USERNAME" VARCHAR2(50 CHAR) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_SENDRECEIVE
-- ----------------------------
CREATE TABLE "FF_SENDRECEIVE" (
"ID" VARCHAR2(50 CHAR) NOT NULL ,
"BUREAUID" VARCHAR2(50 CHAR) NOT NULL ,
"BUREAUNAME" VARCHAR2(200 CHAR) NULL ,
"CREATEDATE" TIMESTAMP(6)  NULL ,
"DEPTID" VARCHAR2(50 CHAR) NOT NULL ,
"GUIDPATH" VARCHAR2(800 CHAR) NULL ,
"NAME" VARCHAR2(200 CHAR) NULL ,
"PERSONID" VARCHAR2(50 CHAR) NULL ,
"TYPE" VARCHAR2(50 CHAR) NULL ,
"USERNAME" VARCHAR2(200 CHAR) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_SIGNATUREPICTURE
-- ----------------------------
CREATE TABLE "FF_SIGNATUREPICTURE" (
"ID" VARCHAR2(38 CHAR) NOT NULL ,
"CREATEDATE" VARCHAR2(50 CHAR) NULL ,
"FILESTOREID" VARCHAR2(50 CHAR) NULL ,
"MODIFYDATE" VARCHAR2(50 CHAR) NULL ,
"TENANTID" VARCHAR2(50 CHAR) NOT NULL ,
"USERID" VARCHAR2(50 CHAR) NOT NULL ,
"USERNAME" VARCHAR2(50 CHAR) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_SP_ATTACHMENT
-- ----------------------------
CREATE TABLE "FF_SP_ATTACHMENT" (
"ID" VARCHAR2(38 CHAR) NOT NULL ,
"FILEBYTES" BLOB NULL ,
"FILENAME" VARCHAR2(200 CHAR) NULL ,
"PARENTID" VARCHAR2(38 CHAR) NULL ,
"FILESIZE" VARCHAR2(255 CHAR) NULL ,
"FILETYPE" VARCHAR2(20 CHAR) NULL ,
"UPLOADPERSON" VARCHAR2(255 CHAR) NULL ,
"UPLOADTIME" TIMESTAMP(6)  NULL ,
"UPLOADURL" VARCHAR2(500 CHAR) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_SP_COOPERATIONFORM
-- ----------------------------
CREATE TABLE "FF_SP_COOPERATIONFORM" (
"ID" VARCHAR2(38 CHAR) NOT NULL ,
"CC_CITY" VARCHAR2(20 CHAR) NULL ,
"CC_CONTACTS" VARCHAR2(40 CHAR) NULL ,
"CC_CONTACTSEMAIL" VARCHAR2(40 CHAR) NULL ,
"CC_CONTACTSMOBILE" VARCHAR2(20 CHAR) NULL ,
"CC_DECLARER" VARCHAR2(100 CHAR) NULL ,
"CC_MAINBUSINESS" VARCHAR2(1000 CHAR) NULL ,
"CC_PROVINCE" VARCHAR2(20 CHAR) NULL ,
"CC_REMARK" VARCHAR2(1000 CHAR) NULL ,
"CONTACTS" VARCHAR2(100 CHAR) NULL ,
"CONTACTSEMAIL" VARCHAR2(50 CHAR) NULL ,
"CONTACTSMOBILE" VARCHAR2(20 CHAR) NULL ,
"CREATETIME" TIMESTAMP(6)  NULL ,
"DECLARER" VARCHAR2(100 CHAR) NULL ,
"FU_CONTACTS" VARCHAR2(40 CHAR) NULL ,
"FU_CONTACTSEMAIL" VARCHAR2(40 CHAR) NULL ,
"FU_CONTACTSMOBILE" VARCHAR2(20 CHAR) NULL ,
"FU_DECLARER" VARCHAR2(100 CHAR) NULL ,
"FU_DESCRIPTION" VARCHAR2(1000 CHAR) NULL ,
"SC_CONTACTS" VARCHAR2(40 CHAR) NULL ,
"SC_CONTACTSEMAIL" VARCHAR2(40 CHAR) NULL ,
"SC_CONTACTSMOBILE" VARCHAR2(20 CHAR) NULL ,
"SC_DECLARER" VARCHAR2(100 CHAR) NULL ,
"SC_PRODUCTNAME" VARCHAR2(200 CHAR) NULL ,
"SC_SUCCESSCASE" VARCHAR2(1000 CHAR) NULL ,
"TYPE" VARCHAR2(20 CHAR) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_SP_DECLAREINFO
-- ----------------------------
CREATE TABLE "FF_SP_DECLAREINFO" (
"ID" VARCHAR2(38 CHAR) NOT NULL ,
"ACCEPTANCENOTICE" VARCHAR2(1000 CHAR) NULL ,
"ACCEPTANCETIME" TIMESTAMP(6)  NULL ,
"APPLYID" VARCHAR2(50 CHAR) NULL ,
"AREA" VARCHAR2(50 CHAR) NULL ,
"BUREAUGUID" VARCHAR2(38 CHAR) NULL ,
"BUREAUNAME" VARCHAR2(38 CHAR) NULL ,
"DECLAREREMAIL" VARCHAR2(50 CHAR) NULL ,
"DECLARERGUID" VARCHAR2(50 CHAR) NULL ,
"DECLARERMOBILE" VARCHAR2(50 CHAR) NULL ,
"DECLARERPERSON" VARCHAR2(500 CHAR) NULL ,
"EMPLOYEEGUID" VARCHAR2(38 CHAR) NULL ,
"EMPLOYEEMOBILE" VARCHAR2(15 CHAR) NULL ,
"EMPLOYEENAME" VARCHAR2(38 CHAR) NULL ,
"FILEBYTES" BLOB NULL ,
"FILENAME" VARCHAR2(200 CHAR) NULL ,
"FINISHNOTICE" VARCHAR2(1000 CHAR) NULL ,
"ITEMGUID" VARCHAR2(38 CHAR) NULL ,
"ITEMNAME" VARCHAR2(250 CHAR) NULL ,
"PROCESSDEFINITIONKEY" VARCHAR2(50 CHAR) NULL ,
"PROCESSINSTANCEID" VARCHAR2(50 CHAR) NULL ,
"PROCESSSERIALNUMBER" VARCHAR2(50 CHAR) NULL ,
"SERIALNUMBER" VARCHAR2(50 CHAR) NULL ,
"STATUS" NUMBER(10) NULL ,
"SUBMITTIME" TIMESTAMP(6)  NULL ,
"TITLE" VARCHAR2(250 CHAR) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_SP_JOBWANTEDFORM
-- ----------------------------
CREATE TABLE "FF_SP_JOBWANTEDFORM" (
"ID" VARCHAR2(38 CHAR) NOT NULL ,
"ADDRESS" VARCHAR2(100 CHAR) NULL ,
"APPLICANT" VARCHAR2(40 CHAR) NULL ,
"AREA" VARCHAR2(50 CHAR) NULL ,
"BIRTHDAY" VARCHAR2(40 CHAR) NULL ,
"CREATETIME" TIMESTAMP(6)  NULL ,
"EDUCATION" VARCHAR2(40 CHAR) NULL ,
"EMAIL" VARCHAR2(40 CHAR) NULL ,
"ETHNIC" VARCHAR2(20 CHAR) NULL ,
"MARRIED" VARCHAR2(10 CHAR) NULL ,
"MOBILE" VARCHAR2(20 CHAR) NULL ,
"POSITION" VARCHAR2(40 CHAR) NULL ,
"SALARY" VARCHAR2(10 CHAR) NULL ,
"SEX" VARCHAR2(10 CHAR) NULL ,
"SPECIALITY" VARCHAR2(2000 CHAR) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_SPEAKINFO
-- ----------------------------
CREATE TABLE "FF_SPEAKINFO" (
"ID" VARCHAR2(38 CHAR) NOT NULL ,
"CONTENT" VARCHAR2(1000 CHAR) NULL ,
"CREATETIME" VARCHAR2(50 CHAR) NULL ,
"DELETED" NUMBER(1) NULL ,
"PROCESSINSTANCEID" VARCHAR2(50 CHAR) NOT NULL ,
"UPDATETIME" VARCHAR2(50 CHAR) NULL ,
"USERID" VARCHAR2(50 CHAR) NULL ,
"USERNAME" VARCHAR2(50 CHAR) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_TABENTITY
-- ----------------------------
CREATE TABLE "FF_TABENTITY" (
"ID" VARCHAR2(38 CHAR) NOT NULL ,
"CREATETIME" VARCHAR2(50 CHAR) NULL ,
"NAME" VARCHAR2(50 CHAR) NULL ,
"TENANTID" VARCHAR2(50 CHAR) NULL ,
"UPDATETIME" VARCHAR2(50 CHAR) NULL ,
"URL" VARCHAR2(50 CHAR) NULL ,
"USERID" VARCHAR2(50 CHAR) NULL ,
"USERNAME" VARCHAR2(50 CHAR) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_TAOHONGTEMPLATE
-- ----------------------------
CREATE TABLE "FF_TAOHONGTEMPLATE" (
"TEMPLATE_GUID" VARCHAR2(38 CHAR) NOT NULL ,
"BUREAU_GUID" VARCHAR2(38 CHAR) NULL ,
"BUREAU_NAME" VARCHAR2(38 CHAR) NULL ,
"TABINDEX" NUMBER(10) NULL ,
"TEMPLATE_CONTENT" BLOB NULL ,
"TEMPLATE_FILENAME" VARCHAR2(100 CHAR) NULL ,
"TEMPLATE_TYPE" VARCHAR2(100 CHAR) NULL ,
"TENANTID" VARCHAR2(50 CHAR) NOT NULL ,
"UPLOADTIME" TIMESTAMP(6)  NOT NULL ,
"USERID" VARCHAR2(38 CHAR) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_TAOHONGTEMPLATETYPE
-- ----------------------------
CREATE TABLE "FF_TAOHONGTEMPLATETYPE" (
"ID" VARCHAR2(38 CHAR) NOT NULL ,
"TABINDEX" NUMBER(10) NULL ,
"TENANTID" VARCHAR2(50 CHAR) NOT NULL ,
"TYPENAME" VARCHAR2(100 CHAR) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Table structure for FF_WORDTEMPLATE
-- ----------------------------
CREATE TABLE "FF_WORDTEMPLATE" (
"ID" VARCHAR2(255 CHAR) NOT NULL ,
"CONTENT" BLOB NULL ,
"DESCRIBES" VARCHAR2(1000 CHAR) NULL ,
"FILENAME" VARCHAR2(50 CHAR) NULL ,
"FILEPATH" VARCHAR2(2000 CHAR) NULL ,
"FILESIZE" VARCHAR2(20 CHAR) NULL ,
"PERSONID" VARCHAR2(50 CHAR) NULL ,
"PERSONNAME" VARCHAR2(100 CHAR) NULL ,
"TENANTID" VARCHAR2(50 CHAR) NULL ,
"UPLOADTIME" TIMESTAMP(6)  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;

-- ----------------------------
-- Indexes structure for table FF_APPROVEITEM
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_APPROVEITEM
-- ----------------------------
ALTER TABLE "FF_APPROVEITEM" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_APPROVEITEM" ADD CHECK ("NAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_APPROVEITEM
-- ----------------------------
ALTER TABLE "FF_APPROVEITEM" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_ASSOCIATEDFILE
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_ASSOCIATEDFILE
-- ----------------------------
ALTER TABLE "FF_ASSOCIATEDFILE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_ASSOCIATEDFILE" ADD CHECK ("PROCESSSERIALNUMBER" IS NOT NULL);
ALTER TABLE "FF_ASSOCIATEDFILE" ADD CHECK ("TENANTID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_ASSOCIATEDFILE
-- ----------------------------
ALTER TABLE "FF_ASSOCIATEDFILE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_ATTACHMENT
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_ATTACHMENT
-- ----------------------------
ALTER TABLE "FF_ATTACHMENT" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_ATTACHMENT
-- ----------------------------
ALTER TABLE "FF_ATTACHMENT" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_AUTOFORMSEQUENCE
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_AUTOFORMSEQUENCE
-- ----------------------------
ALTER TABLE "FF_AUTOFORMSEQUENCE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_AUTOFORMSEQUENCE" ADD CHECK ("TENANTID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_AUTOFORMSEQUENCE
-- ----------------------------
ALTER TABLE "FF_AUTOFORMSEQUENCE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_CHAOSONG
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_CHAOSONG
-- ----------------------------
ALTER TABLE "FF_CHAOSONG" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_CHAOSONG" ADD CHECK ("ITEMID" IS NOT NULL);
ALTER TABLE "FF_CHAOSONG" ADD CHECK ("ITEMNAME" IS NOT NULL);
ALTER TABLE "FF_CHAOSONG" ADD CHECK ("PROCESSINSTANCEID" IS NOT NULL);
ALTER TABLE "FF_CHAOSONG" ADD CHECK ("PROCESSSERIALNUMBER" IS NOT NULL);
ALTER TABLE "FF_CHAOSONG" ADD CHECK ("SYSTEMNAME" IS NOT NULL);
ALTER TABLE "FF_CHAOSONG" ADD CHECK ("TASKID" IS NOT NULL);
ALTER TABLE "FF_CHAOSONG" ADD CHECK ("TENANTID" IS NOT NULL);
ALTER TABLE "FF_CHAOSONG" ADD CHECK ("TITLE" IS NOT NULL);
ALTER TABLE "FF_CHAOSONG" ADD CHECK ("USERID" IS NOT NULL);
ALTER TABLE "FF_CHAOSONG" ADD CHECK ("USERNAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_CHAOSONG
-- ----------------------------
ALTER TABLE "FF_CHAOSONG" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_COMMONBUTTON
-- ----------------------------

-- ----------------------------
-- Uniques structure for table FF_COMMONBUTTON
-- ----------------------------
ALTER TABLE "FF_COMMONBUTTON" ADD UNIQUE ("CUSTOMID");

-- ----------------------------
-- Checks structure for table FF_COMMONBUTTON
-- ----------------------------
ALTER TABLE "FF_COMMONBUTTON" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_COMMONBUTTON" ADD CHECK ("CUSTOMID" IS NOT NULL);
ALTER TABLE "FF_COMMONBUTTON" ADD CHECK ("NAME" IS NOT NULL);
ALTER TABLE "FF_COMMONBUTTON" ADD CHECK ("TENANTID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_COMMONBUTTON
-- ----------------------------
ALTER TABLE "FF_COMMONBUTTON" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_COMMONSENTENCES
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_COMMONSENTENCES
-- ----------------------------
ALTER TABLE "FF_COMMONSENTENCES" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_COMMONSENTENCES" ADD CHECK ("CONTENT" IS NOT NULL);
ALTER TABLE "FF_COMMONSENTENCES" ADD CHECK ("TENANTID" IS NOT NULL);
ALTER TABLE "FF_COMMONSENTENCES" ADD CHECK ("USERID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_COMMONSENTENCES
-- ----------------------------
ALTER TABLE "FF_COMMONSENTENCES" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_COMMONSENTENCESINIT
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_COMMONSENTENCESINIT
-- ----------------------------
ALTER TABLE "FF_COMMONSENTENCESINIT" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_COMMONSENTENCESINIT" ADD CHECK ("USERID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_COMMONSENTENCESINIT
-- ----------------------------
ALTER TABLE "FF_COMMONSENTENCESINIT" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_DOCUMENTNUMBERDETAIL
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_DOCUMENTNUMBERDETAIL
-- ----------------------------
ALTER TABLE "FF_DOCUMENTNUMBERDETAIL" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_DOCUMENTNUMBERDETAIL" ADD CHECK ("CALENDARYEAR" IS NOT NULL);
ALTER TABLE "FF_DOCUMENTNUMBERDETAIL" ADD CHECK ("TENANTID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_DOCUMENTNUMBERDETAIL
-- ----------------------------
ALTER TABLE "FF_DOCUMENTNUMBERDETAIL" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_DOCUMENTWORD
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_DOCUMENTWORD
-- ----------------------------
ALTER TABLE "FF_DOCUMENTWORD" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_DOCUMENTWORD" ADD CHECK ("TENANTID" IS NOT NULL);
ALTER TABLE "FF_DOCUMENTWORD" ADD CHECK ("USERID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_DOCUMENTWORD
-- ----------------------------
ALTER TABLE "FF_DOCUMENTWORD" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_DOCUMENTWORD_HIS
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_DOCUMENTWORD_HIS
-- ----------------------------
ALTER TABLE "FF_DOCUMENTWORD_HIS" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_DOCUMENTWORD_HIS" ADD CHECK ("TENANTID" IS NOT NULL);
ALTER TABLE "FF_DOCUMENTWORD_HIS" ADD CHECK ("USERID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_DOCUMENTWORD_HIS
-- ----------------------------
ALTER TABLE "FF_DOCUMENTWORD_HIS" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_DRAFTENTITY
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_DRAFTENTITY
-- ----------------------------
ALTER TABLE "FF_DRAFTENTITY" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_DRAFTENTITY
-- ----------------------------
ALTER TABLE "FF_DRAFTENTITY" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_DYNAMICROLE
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_DYNAMICROLE
-- ----------------------------
ALTER TABLE "FF_DYNAMICROLE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_DYNAMICROLE" ADD CHECK ("CLASSPATH" IS NOT NULL);
ALTER TABLE "FF_DYNAMICROLE" ADD CHECK ("TENANTID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_DYNAMICROLE
-- ----------------------------
ALTER TABLE "FF_DYNAMICROLE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_ENTRUST
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_ENTRUST
-- ----------------------------
ALTER TABLE "FF_ENTRUST" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_ENTRUST" ADD CHECK ("ASSIGNEEID" IS NOT NULL);
ALTER TABLE "FF_ENTRUST" ADD CHECK ("CREATTIME" IS NOT NULL);
ALTER TABLE "FF_ENTRUST" ADD CHECK ("ENDTIME" IS NOT NULL);
ALTER TABLE "FF_ENTRUST" ADD CHECK ("ITEMID" IS NOT NULL);
ALTER TABLE "FF_ENTRUST" ADD CHECK ("OWNERID" IS NOT NULL);
ALTER TABLE "FF_ENTRUST" ADD CHECK ("STARTTIME" IS NOT NULL);
ALTER TABLE "FF_ENTRUST" ADD CHECK ("UPDATETIME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_ENTRUST
-- ----------------------------
ALTER TABLE "FF_ENTRUST" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_ENTRUST_HISTORY
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_ENTRUST_HISTORY
-- ----------------------------
ALTER TABLE "FF_ENTRUST_HISTORY" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_ENTRUST_HISTORY" ADD CHECK ("ASSIGNEEID" IS NOT NULL);
ALTER TABLE "FF_ENTRUST_HISTORY" ADD CHECK ("CREATTIME" IS NOT NULL);
ALTER TABLE "FF_ENTRUST_HISTORY" ADD CHECK ("ENDTIME" IS NOT NULL);
ALTER TABLE "FF_ENTRUST_HISTORY" ADD CHECK ("ITEMID" IS NOT NULL);
ALTER TABLE "FF_ENTRUST_HISTORY" ADD CHECK ("OWNERID" IS NOT NULL);
ALTER TABLE "FF_ENTRUST_HISTORY" ADD CHECK ("STARTTIME" IS NOT NULL);
ALTER TABLE "FF_ENTRUST_HISTORY" ADD CHECK ("UPDATETIME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_ENTRUST_HISTORY
-- ----------------------------
ALTER TABLE "FF_ENTRUST_HISTORY" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_EXTENDED_CONTENT
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_EXTENDED_CONTENT
-- ----------------------------
ALTER TABLE "FF_EXTENDED_CONTENT" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_EXTENDED_CONTENT" ADD CHECK ("CATEGORY" IS NOT NULL);
ALTER TABLE "FF_EXTENDED_CONTENT" ADD CHECK ("CONTENT" IS NOT NULL);
ALTER TABLE "FF_EXTENDED_CONTENT" ADD CHECK ("PROCESSSERIALNUMBER" IS NOT NULL);
ALTER TABLE "FF_EXTENDED_CONTENT" ADD CHECK ("TENANTID" IS NOT NULL);
ALTER TABLE "FF_EXTENDED_CONTENT" ADD CHECK ("USERID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_EXTENDED_CONTENT
-- ----------------------------
ALTER TABLE "FF_EXTENDED_CONTENT" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_EXTRANETEFORMITEMBIND
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_EXTRANETEFORMITEMBIND
-- ----------------------------
ALTER TABLE "FF_EXTRANETEFORMITEMBIND" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_EXTRANETEFORMITEMBIND" ADD CHECK ("FORMID" IS NOT NULL);
ALTER TABLE "FF_EXTRANETEFORMITEMBIND" ADD CHECK ("ITEMID" IS NOT NULL);
ALTER TABLE "FF_EXTRANETEFORMITEMBIND" ADD CHECK ("TENANTID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_EXTRANETEFORMITEMBIND
-- ----------------------------
ALTER TABLE "FF_EXTRANETEFORMITEMBIND" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_ITEM_BUTTON_ROLE
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_ITEM_BUTTON_ROLE
-- ----------------------------
ALTER TABLE "FF_ITEM_BUTTON_ROLE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_ITEM_BUTTON_ROLE" ADD CHECK ("ITEMBUTTONID" IS NOT NULL);
ALTER TABLE "FF_ITEM_BUTTON_ROLE" ADD CHECK ("ROLEID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_ITEM_BUTTON_ROLE
-- ----------------------------
ALTER TABLE "FF_ITEM_BUTTON_ROLE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_ITEM_BUTTONBIND
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_ITEM_BUTTONBIND
-- ----------------------------
ALTER TABLE "FF_ITEM_BUTTONBIND" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_ITEM_BUTTONBIND" ADD CHECK ("BUTTONID" IS NOT NULL);
ALTER TABLE "FF_ITEM_BUTTONBIND" ADD CHECK ("BUTTONTYPE" IS NOT NULL);
ALTER TABLE "FF_ITEM_BUTTONBIND" ADD CHECK ("ITEMID" IS NOT NULL);
ALTER TABLE "FF_ITEM_BUTTONBIND" ADD CHECK ("PROCESSDEFINITIONID" IS NOT NULL);
ALTER TABLE "FF_ITEM_BUTTONBIND" ADD CHECK ("TASKDEFKEY" IS NOT NULL);
ALTER TABLE "FF_ITEM_BUTTONBIND" ADD CHECK ("TENANTID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_ITEM_BUTTONBIND
-- ----------------------------
ALTER TABLE "FF_ITEM_BUTTONBIND" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_ITEM_EFORMBIND
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_ITEM_EFORMBIND
-- ----------------------------
ALTER TABLE "FF_ITEM_EFORMBIND" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_ITEM_EFORMBIND" ADD CHECK ("FORMID" IS NOT NULL);
ALTER TABLE "FF_ITEM_EFORMBIND" ADD CHECK ("FORMURL" IS NOT NULL);
ALTER TABLE "FF_ITEM_EFORMBIND" ADD CHECK ("ITEMID" IS NOT NULL);
ALTER TABLE "FF_ITEM_EFORMBIND" ADD CHECK ("PROCESSDEFINITIONID" IS NOT NULL);
ALTER TABLE "FF_ITEM_EFORMBIND" ADD CHECK ("TENANTID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_ITEM_EFORMBIND
-- ----------------------------
ALTER TABLE "FF_ITEM_EFORMBIND" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_ITEM_OPINIONFRAME
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_ITEM_OPINIONFRAME
-- ----------------------------
ALTER TABLE "FF_ITEM_OPINIONFRAME" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_ITEM_OPINIONFRAME" ADD CHECK ("ITEMID" IS NOT NULL);
ALTER TABLE "FF_ITEM_OPINIONFRAME" ADD CHECK ("OPINIONFRAMEMARK" IS NOT NULL);
ALTER TABLE "FF_ITEM_OPINIONFRAME" ADD CHECK ("OPINIONFRAMENAME" IS NOT NULL);
ALTER TABLE "FF_ITEM_OPINIONFRAME" ADD CHECK ("PROCESSDEFINITIONID" IS NOT NULL);
ALTER TABLE "FF_ITEM_OPINIONFRAME" ADD CHECK ("TASKDEFKEY" IS NOT NULL);
ALTER TABLE "FF_ITEM_OPINIONFRAME" ADD CHECK ("TENANTID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_ITEM_OPINIONFRAME
-- ----------------------------
ALTER TABLE "FF_ITEM_OPINIONFRAME" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_ITEM_OPINIONFRAME_ROLE
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_ITEM_OPINIONFRAME_ROLE
-- ----------------------------
ALTER TABLE "FF_ITEM_OPINIONFRAME_ROLE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_ITEM_OPINIONFRAME_ROLE" ADD CHECK ("ITEMOPINIONFRAMEID" IS NOT NULL);
ALTER TABLE "FF_ITEM_OPINIONFRAME_ROLE" ADD CHECK ("ROLEID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_ITEM_OPINIONFRAME_ROLE
-- ----------------------------
ALTER TABLE "FF_ITEM_OPINIONFRAME_ROLE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_ITEM_ORGANWORD
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_ITEM_ORGANWORD
-- ----------------------------
ALTER TABLE "FF_ITEM_ORGANWORD" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_ITEM_ORGANWORD" ADD CHECK ("ITEMID" IS NOT NULL);
ALTER TABLE "FF_ITEM_ORGANWORD" ADD CHECK ("ORGANWORDCUSTOM" IS NOT NULL);
ALTER TABLE "FF_ITEM_ORGANWORD" ADD CHECK ("PROCESSDEFINITIONID" IS NOT NULL);
ALTER TABLE "FF_ITEM_ORGANWORD" ADD CHECK ("TASKDEFKEY" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_ITEM_ORGANWORD
-- ----------------------------
ALTER TABLE "FF_ITEM_ORGANWORD" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_ITEM_ORGANWORD_ROLE
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_ITEM_ORGANWORD_ROLE
-- ----------------------------
ALTER TABLE "FF_ITEM_ORGANWORD_ROLE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_ITEM_ORGANWORD_ROLE" ADD CHECK ("ITEMORGANWORDBINDID" IS NOT NULL);
ALTER TABLE "FF_ITEM_ORGANWORD_ROLE" ADD CHECK ("ROLEID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_ITEM_ORGANWORD_ROLE
-- ----------------------------
ALTER TABLE "FF_ITEM_ORGANWORD_ROLE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_ITEM_PERMISSION
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_ITEM_PERMISSION
-- ----------------------------
ALTER TABLE "FF_ITEM_PERMISSION" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_ITEM_PERMISSION" ADD CHECK ("ITEMID" IS NOT NULL);
ALTER TABLE "FF_ITEM_PERMISSION" ADD CHECK ("PROCESSDEFINITIONID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_ITEM_PERMISSION
-- ----------------------------
ALTER TABLE "FF_ITEM_PERMISSION" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_ITEM_PRINTFORM_BIND
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_ITEM_PRINTFORM_BIND
-- ----------------------------
ALTER TABLE "FF_ITEM_PRINTFORM_BIND" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_ITEM_PRINTFORM_BIND" ADD CHECK ("FORMID" IS NOT NULL);
ALTER TABLE "FF_ITEM_PRINTFORM_BIND" ADD CHECK ("FORMURL" IS NOT NULL);
ALTER TABLE "FF_ITEM_PRINTFORM_BIND" ADD CHECK ("ITEMID" IS NOT NULL);
ALTER TABLE "FF_ITEM_PRINTFORM_BIND" ADD CHECK ("PROCESSDEFINITIONID" IS NOT NULL);
ALTER TABLE "FF_ITEM_PRINTFORM_BIND" ADD CHECK ("TENANTID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_ITEM_PRINTFORM_BIND
-- ----------------------------
ALTER TABLE "FF_ITEM_PRINTFORM_BIND" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_ITEM_TABBIND
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_ITEM_TABBIND
-- ----------------------------
ALTER TABLE "FF_ITEM_TABBIND" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_ITEM_TABBIND" ADD CHECK ("ITEMID" IS NOT NULL);
ALTER TABLE "FF_ITEM_TABBIND" ADD CHECK ("PROCESSDEFINITIONID" IS NOT NULL);
ALTER TABLE "FF_ITEM_TABBIND" ADD CHECK ("TABID" IS NOT NULL);
ALTER TABLE "FF_ITEM_TABBIND" ADD CHECK ("TENANTID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_ITEM_TABBIND
-- ----------------------------
ALTER TABLE "FF_ITEM_TABBIND" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_ITEM_TASKCONF
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_ITEM_TASKCONF
-- ----------------------------
ALTER TABLE "FF_ITEM_TASKCONF" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_ITEM_TASKCONF" ADD CHECK ("ITEMID" IS NOT NULL);
ALTER TABLE "FF_ITEM_TASKCONF" ADD CHECK ("PROCESSDEFINITIONID" IS NOT NULL);
ALTER TABLE "FF_ITEM_TASKCONF" ADD CHECK ("SPONSOR" IS NOT NULL);
ALTER TABLE "FF_ITEM_TASKCONF" ADD CHECK ("TASKDEFKEY" IS NOT NULL);
ALTER TABLE "FF_ITEM_TASKCONF" ADD CHECK ("TENANTID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_ITEM_TASKCONF
-- ----------------------------
ALTER TABLE "FF_ITEM_TASKCONF" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_ITEM_WORDTEMPLATE_BIND
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_ITEM_WORDTEMPLATE_BIND
-- ----------------------------
ALTER TABLE "FF_ITEM_WORDTEMPLATE_BIND" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_ITEM_WORDTEMPLATE_BIND" ADD CHECK ("PROCESSDEFINITIONID" IS NOT NULL);
ALTER TABLE "FF_ITEM_WORDTEMPLATE_BIND" ADD CHECK ("TENANTID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_ITEM_WORDTEMPLATE_BIND
-- ----------------------------
ALTER TABLE "FF_ITEM_WORDTEMPLATE_BIND" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_NETWORK_WORKORDERINFO
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_NETWORK_WORKORDERINFO
-- ----------------------------
ALTER TABLE "FF_NETWORK_WORKORDERINFO" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_NETWORK_WORKORDERINFO
-- ----------------------------
ALTER TABLE "FF_NETWORK_WORKORDERINFO" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_OPINION
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_OPINION
-- ----------------------------
ALTER TABLE "FF_OPINION" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_OPINION" ADD CHECK ("CONTENT" IS NOT NULL);
ALTER TABLE "FF_OPINION" ADD CHECK ("OPINIONFRAMEMARK" IS NOT NULL);
ALTER TABLE "FF_OPINION" ADD CHECK ("PROCESSSERIALNUMBER" IS NOT NULL);
ALTER TABLE "FF_OPINION" ADD CHECK ("TENANTID" IS NOT NULL);
ALTER TABLE "FF_OPINION" ADD CHECK ("USERID" IS NOT NULL);
ALTER TABLE "FF_OPINION" ADD CHECK ("USERNAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_OPINION
-- ----------------------------
ALTER TABLE "FF_OPINION" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_OPINIONFRAME
-- ----------------------------

-- ----------------------------
-- Uniques structure for table FF_OPINIONFRAME
-- ----------------------------
ALTER TABLE "FF_OPINIONFRAME" ADD UNIQUE ("MARK");

-- ----------------------------
-- Checks structure for table FF_OPINIONFRAME
-- ----------------------------
ALTER TABLE "FF_OPINIONFRAME" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_OPINIONFRAME" ADD CHECK ("MARK" IS NOT NULL);
ALTER TABLE "FF_OPINIONFRAME" ADD CHECK ("NAME" IS NOT NULL);
ALTER TABLE "FF_OPINIONFRAME" ADD CHECK ("USERID" IS NOT NULL);
ALTER TABLE "FF_OPINIONFRAME" ADD CHECK ("USERNAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_OPINIONFRAME
-- ----------------------------
ALTER TABLE "FF_OPINIONFRAME" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_ORGANWORD
-- ----------------------------

-- ----------------------------
-- Uniques structure for table FF_ORGANWORD
-- ----------------------------
ALTER TABLE "FF_ORGANWORD" ADD UNIQUE ("CUSTOM");

-- ----------------------------
-- Checks structure for table FF_ORGANWORD
-- ----------------------------
ALTER TABLE "FF_ORGANWORD" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_ORGANWORD" ADD CHECK ("USERNAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_ORGANWORD
-- ----------------------------
ALTER TABLE "FF_ORGANWORD" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_ORGANWORD_DETAIL
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_ORGANWORD_DETAIL
-- ----------------------------
ALTER TABLE "FF_ORGANWORD_DETAIL" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_ORGANWORD_DETAIL" ADD CHECK ("CHARACTERVALUE" IS NOT NULL);
ALTER TABLE "FF_ORGANWORD_DETAIL" ADD CHECK ("CREATETIME" IS NOT NULL);
ALTER TABLE "FF_ORGANWORD_DETAIL" ADD CHECK ("CUSTOM" IS NOT NULL);
ALTER TABLE "FF_ORGANWORD_DETAIL" ADD CHECK ("ITEMID" IS NOT NULL);
ALTER TABLE "FF_ORGANWORD_DETAIL" ADD CHECK ("CURRENTNUMBER" IS NOT NULL);
ALTER TABLE "FF_ORGANWORD_DETAIL" ADD CHECK ("TENANTID" IS NOT NULL);
ALTER TABLE "FF_ORGANWORD_DETAIL" ADD CHECK ("YEARS" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_ORGANWORD_DETAIL
-- ----------------------------
ALTER TABLE "FF_ORGANWORD_DETAIL" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_ORGANWORD_PROPTY
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_ORGANWORD_PROPTY
-- ----------------------------
ALTER TABLE "FF_ORGANWORD_PROPTY" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_ORGANWORD_PROPTY" ADD CHECK ("INITNUMBER" IS NOT NULL);
ALTER TABLE "FF_ORGANWORD_PROPTY" ADD CHECK ("TABINDEX" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_ORGANWORD_PROPTY
-- ----------------------------
ALTER TABLE "FF_ORGANWORD_PROPTY" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_ORGANWORD_USEHISTORY
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_ORGANWORD_USEHISTORY
-- ----------------------------
ALTER TABLE "FF_ORGANWORD_USEHISTORY" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_ORGANWORD_USEHISTORY" ADD CHECK ("CREATETIME" IS NOT NULL);
ALTER TABLE "FF_ORGANWORD_USEHISTORY" ADD CHECK ("CUSTOM" IS NOT NULL);
ALTER TABLE "FF_ORGANWORD_USEHISTORY" ADD CHECK ("ITEMID" IS NOT NULL);
ALTER TABLE "FF_ORGANWORD_USEHISTORY" ADD CHECK ("NUMBERSTRING" IS NOT NULL);
ALTER TABLE "FF_ORGANWORD_USEHISTORY" ADD CHECK ("PROCESSSERIALNUMBER" IS NOT NULL);
ALTER TABLE "FF_ORGANWORD_USEHISTORY" ADD CHECK ("TENANTID" IS NOT NULL);
ALTER TABLE "FF_ORGANWORD_USEHISTORY" ADD CHECK ("USERID" IS NOT NULL);
ALTER TABLE "FF_ORGANWORD_USEHISTORY" ADD CHECK ("USERNAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_ORGANWORD_USEHISTORY
-- ----------------------------
ALTER TABLE "FF_ORGANWORD_USEHISTORY" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_PROCESSTRACK
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_PROCESSTRACK
-- ----------------------------
ALTER TABLE "FF_PROCESSTRACK" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_PROCESSTRACK" ADD CHECK ("PROCESSINSTANCEID" IS NOT NULL);
ALTER TABLE "FF_PROCESSTRACK" ADD CHECK ("SENDERNAME" IS NOT NULL);
ALTER TABLE "FF_PROCESSTRACK" ADD CHECK ("TASKID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_PROCESSTRACK
-- ----------------------------
ALTER TABLE "FF_PROCESSTRACK" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_PROCINSTANCERELATIONSHIP
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_PROCINSTANCERELATIONSHIP
-- ----------------------------
ALTER TABLE "FF_PROCINSTANCERELATIONSHIP" ADD CHECK ("PROCINSTANCEID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_PROCINSTANCERELATIONSHIP
-- ----------------------------
ALTER TABLE "FF_PROCINSTANCERELATIONSHIP" ADD PRIMARY KEY ("PROCINSTANCEID");

-- ----------------------------
-- Indexes structure for table FF_REJECTREASON
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_REJECTREASON
-- ----------------------------
ALTER TABLE "FF_REJECTREASON" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_REJECTREASON
-- ----------------------------
ALTER TABLE "FF_REJECTREASON" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_REMINDER
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_REMINDER
-- ----------------------------
ALTER TABLE "FF_REMINDER" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_REMINDER" ADD CHECK ("CREATETIME" IS NOT NULL);
ALTER TABLE "FF_REMINDER" ADD CHECK ("MODIFYTIME" IS NOT NULL);
ALTER TABLE "FF_REMINDER" ADD CHECK ("MSGCONTENT" IS NOT NULL);
ALTER TABLE "FF_REMINDER" ADD CHECK ("PROCINSTID" IS NOT NULL);
ALTER TABLE "FF_REMINDER" ADD CHECK ("REMINDER_MAKE_TYPE" IS NOT NULL);
ALTER TABLE "FF_REMINDER" ADD CHECK ("REMINDER_SEND_TYPE" IS NOT NULL);
ALTER TABLE "FF_REMINDER" ADD CHECK ("SENDERID" IS NOT NULL);
ALTER TABLE "FF_REMINDER" ADD CHECK ("SENDERNAME" IS NOT NULL);
ALTER TABLE "FF_REMINDER" ADD CHECK ("TASKID" IS NOT NULL);
ALTER TABLE "FF_REMINDER" ADD CHECK ("TENANTID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_REMINDER
-- ----------------------------
ALTER TABLE "FF_REMINDER" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_REMINDERDEFINE
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_REMINDERDEFINE
-- ----------------------------
ALTER TABLE "FF_REMINDERDEFINE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_REMINDERDEFINE" ADD CHECK ("DAY_TYPE" IS NOT NULL);
ALTER TABLE "FF_REMINDERDEFINE" ADD CHECK ("MSGTEMPLATE" IS NOT NULL);
ALTER TABLE "FF_REMINDERDEFINE" ADD CHECK ("PROCESSDEFINITIONID" IS NOT NULL);
ALTER TABLE "FF_REMINDERDEFINE" ADD CHECK ("REMINDERDEFINE_AUTOMATIC" IS NOT NULL);
ALTER TABLE "FF_REMINDERDEFINE" ADD CHECK ("REMINDERDEFINE_TYPE" IS NOT NULL);
ALTER TABLE "FF_REMINDERDEFINE" ADD CHECK ("TENANTID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_REMINDERDEFINE
-- ----------------------------
ALTER TABLE "FF_REMINDERDEFINE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_SENDBUTTON
-- ----------------------------

-- ----------------------------
-- Uniques structure for table FF_SENDBUTTON
-- ----------------------------
ALTER TABLE "FF_SENDBUTTON" ADD UNIQUE ("CUSTOMID");

-- ----------------------------
-- Checks structure for table FF_SENDBUTTON
-- ----------------------------
ALTER TABLE "FF_SENDBUTTON" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_SENDBUTTON" ADD CHECK ("CUSTOMID" IS NOT NULL);
ALTER TABLE "FF_SENDBUTTON" ADD CHECK ("NAME" IS NOT NULL);
ALTER TABLE "FF_SENDBUTTON" ADD CHECK ("TENANTID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_SENDBUTTON
-- ----------------------------
ALTER TABLE "FF_SENDBUTTON" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_SENDRECEIVE
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_SENDRECEIVE
-- ----------------------------
ALTER TABLE "FF_SENDRECEIVE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_SENDRECEIVE" ADD CHECK ("BUREAUID" IS NOT NULL);
ALTER TABLE "FF_SENDRECEIVE" ADD CHECK ("DEPTID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_SENDRECEIVE
-- ----------------------------
ALTER TABLE "FF_SENDRECEIVE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_SIGNATUREPICTURE
-- ----------------------------

-- ----------------------------
-- Uniques structure for table FF_SIGNATUREPICTURE
-- ----------------------------
ALTER TABLE "FF_SIGNATUREPICTURE" ADD UNIQUE ("USERID");

-- ----------------------------
-- Checks structure for table FF_SIGNATUREPICTURE
-- ----------------------------
ALTER TABLE "FF_SIGNATUREPICTURE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_SIGNATUREPICTURE" ADD CHECK ("TENANTID" IS NOT NULL);
ALTER TABLE "FF_SIGNATUREPICTURE" ADD CHECK ("USERID" IS NOT NULL);
ALTER TABLE "FF_SIGNATUREPICTURE" ADD CHECK ("USERNAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_SIGNATUREPICTURE
-- ----------------------------
ALTER TABLE "FF_SIGNATUREPICTURE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_SP_ATTACHMENT
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_SP_ATTACHMENT
-- ----------------------------
ALTER TABLE "FF_SP_ATTACHMENT" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_SP_ATTACHMENT
-- ----------------------------
ALTER TABLE "FF_SP_ATTACHMENT" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_SP_COOPERATIONFORM
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_SP_COOPERATIONFORM
-- ----------------------------
ALTER TABLE "FF_SP_COOPERATIONFORM" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_SP_COOPERATIONFORM
-- ----------------------------
ALTER TABLE "FF_SP_COOPERATIONFORM" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_SP_DECLAREINFO
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_SP_DECLAREINFO
-- ----------------------------
ALTER TABLE "FF_SP_DECLAREINFO" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_SP_DECLAREINFO
-- ----------------------------
ALTER TABLE "FF_SP_DECLAREINFO" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_SP_JOBWANTEDFORM
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_SP_JOBWANTEDFORM
-- ----------------------------
ALTER TABLE "FF_SP_JOBWANTEDFORM" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_SP_JOBWANTEDFORM
-- ----------------------------
ALTER TABLE "FF_SP_JOBWANTEDFORM" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_SPEAKINFO
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_SPEAKINFO
-- ----------------------------
ALTER TABLE "FF_SPEAKINFO" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_SPEAKINFO" ADD CHECK ("PROCESSINSTANCEID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_SPEAKINFO
-- ----------------------------
ALTER TABLE "FF_SPEAKINFO" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_TABENTITY
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_TABENTITY
-- ----------------------------
ALTER TABLE "FF_TABENTITY" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_TABENTITY
-- ----------------------------
ALTER TABLE "FF_TABENTITY" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_TAOHONGTEMPLATE
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_TAOHONGTEMPLATE
-- ----------------------------
ALTER TABLE "FF_TAOHONGTEMPLATE" ADD CHECK ("TEMPLATE_GUID" IS NOT NULL);
ALTER TABLE "FF_TAOHONGTEMPLATE" ADD CHECK ("TENANTID" IS NOT NULL);
ALTER TABLE "FF_TAOHONGTEMPLATE" ADD CHECK ("UPLOADTIME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_TAOHONGTEMPLATE
-- ----------------------------
ALTER TABLE "FF_TAOHONGTEMPLATE" ADD PRIMARY KEY ("TEMPLATE_GUID");

-- ----------------------------
-- Indexes structure for table FF_TAOHONGTEMPLATETYPE
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_TAOHONGTEMPLATETYPE
-- ----------------------------
ALTER TABLE "FF_TAOHONGTEMPLATETYPE" ADD CHECK ("ID" IS NOT NULL);
ALTER TABLE "FF_TAOHONGTEMPLATETYPE" ADD CHECK ("TENANTID" IS NOT NULL);
ALTER TABLE "FF_TAOHONGTEMPLATETYPE" ADD CHECK ("TYPENAME" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_TAOHONGTEMPLATETYPE
-- ----------------------------
ALTER TABLE "FF_TAOHONGTEMPLATETYPE" ADD PRIMARY KEY ("ID");

-- ----------------------------
-- Indexes structure for table FF_WORDTEMPLATE
-- ----------------------------

-- ----------------------------
-- Checks structure for table FF_WORDTEMPLATE
-- ----------------------------
ALTER TABLE "FF_WORDTEMPLATE" ADD CHECK ("ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table FF_WORDTEMPLATE
-- ----------------------------
ALTER TABLE "FF_WORDTEMPLATE" ADD PRIMARY KEY ("ID");
